### ISSUE TITLE
TransactionMapping fromDTO fails to load transactions

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#107]
1. Expected behavior and actual behavior.

Using ``TransactionMapping`` class we can create Transactions using the DTO format. Once we turn a transaction to DTO, and try to recreate it using  ``TransactionMapping.fromDTO(transaction.toJSON())`` we get the following error:

> TypeError: Cannot read property 'type' of undefined from \nem2sdk\dist\src\infrastructure\transaction\CreateTransactionFromDTO.js:60:36.

2. Steps to reproduce the problem.

``` typescript
    const transferTransaction = TransferTransaction.create(
        Deadline.create(),
        Address.createFromRawAddress('SAGYCE-QM5SK2-TGFUC5-Z5GZJR-ATKTBS-UQQMMH-KW5B'),
        [NetworkCurrencyMosaic.createRelative(10)],
        PlainMessage.create('hello'),
        NetworkType.MIJIN_TEST
    );
    TransactionMapping.createFromDTO(transferTransaction.toJSON());
```

**Comment by rg911** [comment]
Ah. looks like swagger DTO wrapped transactions into a 'transaction' property, haha!
