### ISSUE TITLE
how ro reserialize signedTransactionRaw.payload

### ISSUE THREAD

**Issue by 9zero** [nemtech/nem2-sdk-typescript-javascript#11]
how ro reserialize signedTransactionRaw.payload

**Comment by aleixmorgadas** [comment]
We haven't a way to deserialize the transaction payload yet, we want to add it near before getting a release candidate version. We hadn't had a case in the early stage that required it. Do you need it for some specific use case? or just nice to have?

**Comment by 9zero** [comment]
such as: collect cosignatures offline

**Comment by aleixmorgadas** [comment]
That's the main use case, it can be stored as JSON or as binary to be later signed offline. Binary could be simpler to deal with.

The current implementation is made using `flatbuffers` and we just support serialization, it's planned to replace `flatbuffers` by [catbuffers](https://github.com/nemtech/catbuffer). It will support serialize and deserialize a transaction payload.

**Comment by aleixmorgadas** [comment]
closing this issue since it's a planned feature.
