### ISSUE TITLE
signWithCosignatories method should not require all cosignatories

### ISSUE THREAD

**Issue by rg911** [nemtech/nem2-sdk-typescript-javascript#112]
Aggregated transaction signWithCosignatories current require both initiator Account and cosigners accounts. It is impossible to cosign **aggregated complete transactions** off-chain. 

`signWithCosignatories` method should only take the cosigner's key 

Scenario below

*1. Bob:*

`const aggr = AggregateTransaction.create(...);
const payload = bobAccount.sign(aggr);`

*2. Bob sends the _payload_ to Alice.*

*3. Alice:*

```const aggr = TransactionMapping.createFromPayload(payload)
const signed = aggr.signWithCosignatories([aliceAccount]);
transactionHttp.announce(aggr).subscribe((response) => { console.log("announce: " + signed.hash); }```

**Comment by rg911** [comment]
To recreate the transaction using Bob and Carol cosignatures:

```const aggregateTransaction = AggregateTransaction.createComplete(
    Deadline.create(),
    [
        AtoBTx.toAggregate(accountA.publicAccount),
        BtoATx.toAggregate(accountB.publicAccount),
        CtoATx.toAggregate(accountC.publicAccount)],
    NetworkType.MIJIN_TEST,
    [ new AggregateTransactionCosignature(BobSignature, PublicAccount.createFromPublicKey(Bob's PublicKey),
     new AggregateTransactionCosignature(CarolSignature, PublicAccount.createFromPublicKey(Carol's PublicKey)]
)```

**Comment by dgarcia360** [comment]
Some problems after recreating the transaction using Bob and Carol cosignatures:

* The deadline will differ from the previous transaction created.
* Feels weird to have to define again the same transaction.
* Feels weird to have to sign the transaction again.
* I could not announce the transaction. After running scenario 02.1, line  ``<AggregateTransaction>TransactionMapping.createFromPayload(signedTransactionPayload);``  the console raises ``JavaScript heap out of memory``.

**Comment by jontey** [comment]
Referring to `<AggregateTransaction>TransactionMapping.createFromPayload(signedTransactionPayload);`

Would it make more sense to pass the aggregate transaction rather than the signed transaction?

Actually, if you pass the signed transaction around, then technically it would be possible for the wallet to show how many cosigners have signed the ACT at this point

**Comment by evias** [comment]
Yes @jontey thats possible - but both Bob and Carol, will send their signed payload to Alice, and those payloads will both hold only 1 signature more. This is partly why aggregate bonded makes much more sense as it will gather signatures through partial transactions...

I feel like @dgarcia360's point on "redefining the transaction" is right. We need something that accepts `public key` and `signatures` and will simply push those into the ACT, seems like something possible @rg911  ?

Thanks for the contribs guys :+1:

**Comment by rg911** [comment]
My comments below
@dgarcia360 @jontey @evias 

- The deadline will differ from the previous transaction created.

   Rather than using `Deadline.create()`,  `TransactionMap.createFromPayload()` should take care of 'deadline' value from payload.

- Feels weird to have to define again the same transaction (already done in 01).

     Agree with this point but not sure how to avoid this as actions are off chain. Signature is created based on signing a transaction. So that the ACT must exist first. One scenario I can think of is: assuming Bob and Carol both "agreed" to create the ACT `proposed` by Alice, Bob and Carol create the same ACT individually off-chain, sign and send to Alice. Alice then consolidate the 'signature' & 'public key` to form a new ACT (with Bob's and Carol's in cosignatories array), Alice then sign it and announce it. In this scenario each party only need to create the transaction once? But this is down to how the off-chain system is setup. I am not 100% sure about this approach. Is it possible?

     @evias if this scenario is what you mean, we can possibly expose a new methods simply extract `signer` and `signature` from the payload.

- Feels weird to sign the transaction again (already done in 01).

     There's also a method `Transaction.serialize()` exposed in recent merge which allow to serialize an unsigned transaction. So the signature and signer fields should read `000000000....` . In theory, Alice don't have to sign anything when creating the transaction. She can just send serialized unsigned payload to Bob and Carol for signing??   

- I could not announce the transaction. After running scenario 02.1, line <AggregateTransaction>TransactionMapping.createFromPayload(signedTransactionPayload); the console raises JavaScript heap out of memory.

     Need to have a look at this one.

**Comment by rg911** [comment]
one more thing on this one!
the method `const cosignatureTransaction = CosignatureTransaction.create(aggregateTransaction);` can only be called once the aggregated transaction has been announced. I don't think it will cope with this scenario??  @dgarcia360
