### ISSUE TITLE
Unable to fetch transactions using account http: Error: uintArray must be be an array of two uint numbers

### ISSUE THREAD

**Issue by wzulfikar** [nemtech/nem2-sdk-typescript-javascript#113]
**1. Expected behavior and actual behavior.**

Expected to get transactions but got error instead. I tracked the offending code (based on error trace) and it brought me here: https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/9cfecb1320b8ef8929f610c29a80fb26a6de2ef0/src/infrastructure/transaction/CreateTransactionFromDTO.ts#L81

I suspect that the culprit was because the type of `fee` from api endpoint is string (not number) which makes the conditional looks like this:
```
→ new UInt64(transactionDTO.transaction.fee || [0, 0])
→ new UInt64('0' || [0, 0])
→ new UInt64('0')
```
The fallback to `[0,0]` (the arg expected by `UInt64`) never happen because the left hand side of the conditional is `'0'` (string), not `0` (number). here's another code to bring other context:
![Screen Shot 2019-04-10 at 4 54 14 PM](https://user-images.githubusercontent.com/7823011/55865648-64cce780-5bb1-11e9-9f8a-fd2d9ac2fa80.png)

_But then_, i checked [account's transactions](http://13.114.200.132:3000/account/565059F55E68F904214E8BE1D610B5BBEA4CE46CC13D246D45BC1DAE5D32A0D2/transactions) and there's no such thing as `fee`; there's only `maxFee` instead.

**2. Steps to reproduce the problem.**
I created a repro code at repl.it: https://repl.it/@wzulfikar/nem2-sdk-dto-error. Run the code and the error will show up.
![Screen Shot 2019-04-10 at 4 34 23 PM](https://user-images.githubusercontent.com/7823011/55864479-27675a80-5baf-11e9-8de0-ccecfd206d9b.png)

**3. Specifications like the version of the project, operating system, or hardware.**
Typescript, with nem2-sdk v0.11.2.

**Comment by rg911** [comment]
Hi @wzulfikar 
Thanks for raising the issue, please be aware there's an open PR for [Fees](https://github.com/nemtech/nem2-sdk-typescript-javascript/pull/101)

However, the rest payload seems interesting. I think the `maxFee` should be a number rather than `string` which you are right.

**Comment by wzulfikar** [comment]
Thanks for the prompt response. Yep, i was about to also attach #74, #75 for more context. 

Btw, there seems to be some discrepancy in npm package (or maybe i'm just tripping): the `dist` code in npm (v0.11.2) has `CreateTransactionFromDTO.js` with `maxFee` in it, but the [tarball from release page](https://github.com/nemtech/nem2-sdk-typescript-javascript/archive/v0.11.2.tar.gz) has the code with `fee` (not `maxFee`). Not sure if this should concern you, just putting it here.

**Comment by evias** [comment]
pinging @Vektrat here as well as this could be a format problem origination from catapult-rest (maxFee as a number).

Regarding the discrepancy in npm package, this is something i will have a look at too :+1:

Currently addressing other issues in PR #101  - Thanks for reporting.

**Comment by rg911** [comment]
> Thanks for the prompt response. Yep, i was about to also attach #74, #75 for more context.
> 
> Btw, there seems to be some discrepancy in npm package (or maybe i'm just tripping): the `dist` code in npm (v0.11.2) has `CreateTransactionFromDTO.js` with `maxFee` in it, but the [tarball from release page](https://github.com/nemtech/nem2-sdk-typescript-javascript/archive/v0.11.2.tar.gz) has the code with `fee` (not `maxFee`). Not sure if this should concern you, just putting it here.

`maxFee` is definitely not release yet. We are still working on the PR.

**Comment by wzulfikar** [comment]
Roger👌

**Comment by wzulfikar** [comment]
Just saw that the `maxFee` at [http://13.114.200.132:3000](http://13.114.200.132:3000/transaction/2788E237517229DDE835EC7DBA0B85333607377CF3E87DEB838C1246F655F988) now uses array, just like previous `fee`.  

![Screen Shot 2019-04-10 at 11 22 22 PM](https://user-images.githubusercontent.com/7823011/55892131-51893e80-5be8-11e9-9891-5472d89a4a19.png)

The repro code (https://repl.it/@wzulfikar/nem2-sdk-dto-error) now works correctly. My side looks good, I'm ok with closing this.

**Comment by rg911** [comment]
Closed as issue fixed on testnet

**Comment by evias** [comment]
@wzulfikar can you try with latest v0.11.3 and give us an update whether this is fixed?

Also, regarding npm differences i think whe  you checked, master was well ahead of latest release on npm, that may explain why versions were different.

**Comment by wzulfikar** [comment]
- [x] Changed nem2-sdk from 0.11.2 to 0.11.3 in [repro code](https://repl.it/@wzulfikar/nem2-sdk-dto-error) and it works
- [x] Double-checked the issue by running my own code in local computer (not on browser via repl.it) also works
- [x] The code in `dist` from npm package (v0.11.3) now matches the one from [github tarball of same version](https://github.com/nemtech/nem2-sdk-typescript-javascript/archive/v0.11.3.tar.gz)

Things're looking good to me 👌
