### ISSUE TITLE
travis-ci returns OK but it fails

### ISSUE THREAD

**Issue by aleixmorgadas** [nemtech/nem2-sdk-typescript-javascript#123]
https://travis-ci.org/nemtech/nem2-sdk-typescript-javascript/jobs/519583017

**Comment by evias** [comment]
more info on this topic:

- Travis build for nodejs v8 **fails** : https://travis-ci.org/nemtech/nem2-sdk-typescript-javascript/jobs/521684274#L469
- `npm run test:cov | coveralls` command is origin of the error.
