### ISSUE TITLE
Permit Keccak SHA3-256 in Public Key to Address generation

### ISSUE THREAD

**Issue by rg911** [nemtech/nem2-sdk-typescript-javascript#128]
Address generation should allow to choose between non-keccak sha3-256 and keccak sha3-256.

Current address generation uses non-keccak by default. Also to enable keccak256 algorithm for `publicKeyToAdderss()`.

Dependency: [Nem2-Lib Issue 30](https://github.com/nemtech/nem2-library-js/issues/30)

**Comment by evias** [comment]
merged in nemtech/nem2-sdk-typescript-javascript@da9f0fe
