### ISSUE TITLE
Failed to test encrypted message

### ISSUE THREAD

**Issue by wzulfikar** [nemtech/nem2-sdk-typescript-javascript#132]
**1. Expected behavior and actual behavior.**
Expected to decrypt encrypted message but returns empty string.

**2. Steps to reproduce the problem.**
- pass `recipient.publicAccount` instead of `account.publicAccount` (sender's public account)
https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/3ef71309ab05ccb603c00ada86f2008faf2e50b0/test/model/transaction/EncryptedMessage.spec.ts#L35-L39

  What confuses is me is line 37 of above test code: I don't understand why would the `account` that encrypts message used again to decrypt the encrypted message, while passing the public account of that same `account` (symmetric).

  Shouldn't it be the `senderAccount` that does the `.encryptMessage()` (repro code line 39-41) and followed by `recipientAccount` that decrypts the message subsequently (repro code line 44-46)? 
   
  repro code: https://repl.it/@wzulfikar/repro-codenem2-sdk-encrypted-message

  ![Screen Shot 2019-04-26 at 11 17 19 PM](https://user-images.githubusercontent.com/7823011/56822073-340bd400-687a-11e9-8b8d-6def2fdc4e1e.png)

**3. Specifications like the version of the project, operating system, or hardware.**
- TypeScript v3.3.3 (via repl.it)
- nem2-sdk v0.11.5

**P.S:**
I'm not sure if encrypted message is still under development, but since i saw the test and the `EncryptedMessage` is exported in v0.11.5, I wanted to test and see if I understand it correctly.

**Comment by rg911** [comment]
👍

**Comment by rg911** [comment]
hey @wzulfikar , thanks for reporting this issue. It was indeed a bug we spotted which used wrong hash algorithm in shared key derive method. 👍
