### ISSUE TITLE
Suggestions to improve AccountProperties

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#134]
Feedback after using the feature ``AccountPropertyTransaction``:

1) ``AccountPropertyTransaction.createAddressFilter`` could  be created with a different class (e.g. "FilterModification" or just "Filter"). The reason behind is to follow the same approach already implemented in [MultisigCosignatoryModification](https://nemtech.github.io/guides/account/modifying-a-multisig-account.html#adding-a-new-cosignatory) when sending a multisig transaction.

**Current approach**
```
const filter = AccountPropertyTransaction
    .createAddressFilter(
        PropertyModificationType.Add,
        Address.createFromRawAddress('SC5DT5Y4DZ7ATYFSWSUX76FAWL6O4ZS2UZ5QSCWF')
    );
```
**Proposed approach**

```
const filter = new FilterModification(
    PropertyModificationType.Add, 
    Address.createFromRawAddress('SC5DT5Y4DZ7ATYFSWSUX76FAWL6O4ZS2UZ5QSCWF')
);
```

or

```
const filter = FilterModification.createForAddress(
    PropertyModificationType.Add, 
    Address.createFromRawAddress('SC5DT5Y4DZ7ATYFSWSUX76FAWL6O4ZS2UZ5QSCWF')
);
```

2) ``createEntityTypeFilter(modificationType: PropertyModificationType, entityType: number)`` accepts a number as an entityType parameter. To reduce typing errors, it would be better to limit the parameter to the [TransactionType](https://nemtech.github.io/nem2-sdk-typescript-javascript/classes/_model_transaction_transactiontype_.transactiontype.html) enumeration.

**Comment by rg911** [comment]
Fixed. should support both constructor / static method creation.
