### ISSUE TITLE
Error: "HashType and Secret have incompatible length or not hexadecimal string"

### ISSUE THREAD

**Issue by decentraliser** [nemtech/nem2-sdk-typescript-javascript#141]
1. Expected behavior and actual behavior.
`accountHttp.transactions` not throwing? when fetching the following transaction:

`99174671B5B28D4A729AC7AAB3A2A4F13B72206EE916CD3AC07C794B572A1210`

2. Steps to reproduce the problem.
get this transaction through a  `accountHttp.transactions` call

current link:
http://13.114.200.132:3000/account/AC1A6E1D8DE5B17D2C6B1293F1CAD3829EEACF38D09311BB3C8E5A880092DE26/transactions?pageSize=10

3. Specifications like the version of the project, operating system, or hardware.
 "nem2-sdk": {
      "version": "0.11.5",

**Comment by rg911** [comment]
@decentraliser It's fixed already
check this out 
https://github.com/nemtech/nem2-sdk-typescript-javascript/issues/138
and 
https://github.com/nemtech/nem2-library-js/pull/39
