### ISSUE TITLE
[Elephant] Consensus mechanism update to PoS+ (collateral models updates)

### ISSUE THREAD

**Issue by evias** [nemtech/nem2-sdk-typescript-javascript#142]
When the PoS+ consensus mechanism has been implemented, there is a need to check the related models for any update on the core side.

Following is the task assignment in milestone Dragon for catapult-server: https://github.com/nemtech/catapult-server/issues/26

--

`AccountState` model in catapult-server will be updated to hold `AccountImportanceInputs` which aggregates sets of T and N, where `T` is a total of fees paid by an account in period P and `N` is the number of times an account is the beneficiary of a block.

Ultimately, the SDK should provide with models for representing these inputs.

:warning: This task is linked to a needed catapult-rest discussion about account importance input retrievals.

**Comment by rg911** [comment]
`importance` and `importanceHeight` fields come with latest E3 schema changes.
