### ISSUE TITLE
[Elephant] Persistent Harvesting Delegation Unlocking

### ISSUE THREAD

**Issue by evias** [nemtech/nem2-sdk-typescript-javascript#143]
Following task assignment describes the Harvesting Account Unlocking mechanism for the catapult-server project: https://github.com/nemtech/catapult-server/issues/15

-- 

### Problem Statement

When a node is restarted, existing delegated harvesters need to reconnect. In Catapult this is more undesired because the beneficiary designated by the node owner would lose income when node owner is not running with full slots.

### Scope of Solution

Delegated harvestes that want to harvest with a specific node owner will need to send a **pre-defined / special message** (via a transfer transaction) to the node owner to be elligible for  harvesting on that node. On the catapult-server side, a file will be saved on disk to **persist the information about elligible harvesters** such that after restart of nodes, those harvesters don't need to reconnect.

This solution will work with a specific type of message contained in a TransferTransaction. The SDK should provide with a class that takes care of that payload formatting accordingly, proposed class names include:

- `HarvestingPersistenceTransaction` extends TransferTransaction
- `PersistHarvestingTransaction` extends TransferTransaction
- `PersistentHarvestingDelegationRequestTransaction` extends TransferTransaction
- `PersistentDelegationRequestTransaction` extends TransferTransaction

@dgarcia360 please to provide with your opinion as well.

**Comment by dgarcia360** [comment]
Here you have some more info on how Persistent Harvesting Delegation Unlocking works (WIP):

https://github.com/nemtech/nem2-docs/pull/241/files

**Encrypted message**

``[8-byte marker] [32-byte salt] [encrypted-data]``

* **8-byte marker**: FE CC 71 C7 64 BF E5 98
* **salt**:  used to derive sharedkeys (DeriveSharedKey(senderPriv, recipientPub, salt))
* **encrypted-data**:  [16-byte AES initialization vector] [padded-encrypted-key]
* **padded-encrypted-key**: encrypt( [private key of the delegated account || padding ] )

**Decrypt message**
``[16-byte AES initialization vector] [harvesting key] [up-to 16-bytes padding]``
