### ISSUE TITLE
Adapt sign / verify logic for better replay protection with cross-network capacities

### ISSUE THREAD

**Issue by evias** [nemtech/nem2-sdk-typescript-javascript#145]
Following the implementation of a `network guid` to improve replay protection within Catapult networks, the **sign and verify** logic will need to be _adapted_ to work with newly introduced `network guid`.

More details will follow before work on this task can begin.

**Comment by evias** [comment]
@rg911 this is shifted with dragon's `generationHash`, no ?

**Comment by rg911** [comment]
oh, yes, this one can be closed now
