### ISSUE TITLE
AccountHttp.transactions outputs aggregate transactions supplementary data

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#150]
**1. Expected behavior and actual behavior.**

``accountHttp.transactions(publicKey)`` should return an ``Observable<Transaction[]>``. 

After subscribing the observable, and logging the output, the SDK is returning supplemental data if one of the transactions in the array is an aggregate transaction.

**2. Steps to reproduce the problem.**

Run in a new file the following snippet with an account that has participated in an aggregate transaction:

```
const accountHttp = new AccountHttp(nodeUrl);
const publicAccount = PublicAccount.createFromPublicKey(publicKey, NetworkType.MIJIN_TEST);
accountHttp.transactions(publicAccount ).subscribe(x=> console.log(x));
```
You will get supplemental data at the beggining about aggregate transactions, and then the expected array of transactions.

**3. Specifications like the version of the project, operating system, or hardware.**
* nem2-sdk 0.11.5

**Comment by rg911** [comment]
The debug codes left in the released package from last release but not on our master branch. This only affects console output, functionality will be fine.  Next release should fix it automatically but will double check.
