### ISSUE TITLE
is Keypair.sign from nem-sdk and Account.signData from nem2-sdk should return different value or the same?

### ISSUE THREAD

**Issue by aizaiz** [nemtech/nem2-sdk-typescript-javascript#16]
@aleixmorgadas  I have tried to sign the data using signData method from Account class in nem2-sdk, but the result is different when I tried to sign using Keypair.sign from nem-sdk.

when I saw the name of the function, I thought it supposed to return same value. please need confirmation. 

```
import * as nemSDK from 'nem-sdk';
import { Account, NetworkType } from 'nem2-sdk';

const nem = nemSDK.default;

const data = 'I am so awesome as always';
const privateKey = 'AB73CCA88C527143CB14C253369364DF95EE8CF83061396F4E724FFC8EF9A779';

// sign using nem-sdk
const keypair = nem.crypto.keyPair.create(privateKey);
console.log(keypair.sign(data).toString());
// result = 3f14883516b094a245228d3dcb49c740a38e4453878d751d56a7b210247dc45bb436a3a807f553538734f4142bfc38d7496cd9e0301bc485cb73f90a2dc20b08

// sign using nem2-sdk
const account = Account.createFromPrivateKey(privateKey, NetworkType.MIJIN_TEST);
console.log(account.signData(data));
// result = 315EE0FA462A1E68EB91E1729EBADB0FBA7938777E637A644E0F7A5C0BC865AE63F121FCB31D23423C2197F41F66ACA96ED30AB7C74229346AB15E3BD83EBF00

```

**Comment by aleixmorgadas** [comment]
the behaviour is correct. 

`signData` from nem2-sdk converts the input to uint8array, so, if you want the same result from nem2-library and nem2-sdk, you will have to convert at nem2-library the input to uint8array before using sign.

**Comment by aizaiz** [comment]
@aleixmorgadas it's not between nem2-library and nem2-sdk, but between nem-sdk(nis1) and nem2-sdk(catapult)

**Comment by aleixmorgadas** [comment]
fast read the question. Yes, it's the desired behaviour. Since the hash algorithm between public and private network changes.

Main Net & Test Net uses Keccak
Mijin & Mijin Test uses SHA3

When the nem2-sdk has the main net compatibility, it will return the same result :smile:
