### ISSUE TITLE
Unconfirmed feature: Tamper-Proof Account Properties & Mosaic Constraints

### ISSUE THREAD

**Issue by evias** [nemtech/nem2-sdk-typescript-javascript#167]
> Current implementation of account properties are inherently mutable and not sticky. They can prevent accidental misuse but provide no defense in the case of a hacked account.

> Explicit locking or unlocking of property changes would provide a better defense to hackers. There are two possible options:
\
> Time lock: Automatically freeze property changes after a certain period of time
> Hash lock: Explicitly freeze property changes until a secret proof is provided

:warning: With regards to this implementation it is required to take confirmation of the details of feature implementations in catapult-server. Current state of the Issue is that this feature is not yet confirmed to be delivered.

According to the proposed implementation plan, new transaction type(s) may be added:

- `SecretPropertyLockTransaction`
- `SecretConstraintLockTransaction`
- `TimePropertyLockTransaction`: in case of both options being implemented.
- `TimeConstraintLockTransaction`: in case of both options being implemented.

More details will be added to this task at a later point.

**Comment by rg911** [comment]
@dgarcia360 @evias Do we have more info about this issue now?

**Comment by dgarcia360** [comment]
Yes, it seems that this feature is not going to be implemented, at least for RC. We can close the issue for now.
