### ISSUE TITLE
Backup simpleWallet

### ISSUE THREAD

**Issue by hungtranqn** [nemtech/nem2-sdk-typescript-javascript#174]
Hello, In nem-library (nem1) we can backup simpleWallet form string
` static readFromWLT(wlt: string): SimpleWallet;`

But nem2-sdk does not have method backup form string or json text

Can someone help me ? Thanks.

**Comment by rg911** [comment]
Can you post the link to NIS1 code pls

**Comment by hungtranqn** [comment]
Sorry about my bad question,
link: https://github.com/NemProject/nem-library-ts/blob/master/src/models/wallet/SimpleWallet.ts

**Comment by rg911** [comment]
is this issue still valid? 
@hungtranqn @evias
