### ISSUE TITLE
utf8ToHex in Convert.ts doesn't add insignificant zero while converting 0-15 control characters

### ISSUE THREAD

**Issue by yaaccount** [nemtech/nem2-sdk-typescript-javascript#175]
Which will probably render encrypt/decrypt not working on strings containing 0x00-0x0f.
Same issue in convert.js in the js lib.

**Comment by rg911** [comment]
seems working fine for me

`Convert.utf8ToHex('00x0 Hello Word')` => `303078302048656c6c6f20576f7264`

**Comment by yaaccount** [comment]
Try String.fromCodePoint(0x00) + "Hello world"

**Comment by rg911** [comment]
Addressed. well spotted @yaaccount 👍

**Comment by evias** [comment]
fixed in 0.12.3
