### ISSUE TITLE
Mosaic Info duration and divisibility are inversed in MosaicInfo since 0.12.2

### ISSUE THREAD

**Issue by decentraliser** [nemtech/nem2-sdk-typescript-javascript#183]
1. Expected behaviour and actual behaviour.
using `mosaicsAmountViewFromAddress`, getting this object:

[{"meta":{"id":"5CF23A4D0C82D1D7E5B53DEE"},"mosaic":{"mosaicId":[764009797,915603349],"supply":[2225904512,2090353],"height":[1,0],"owner":"DB06E6C3F6976324BA215D7D1F2D4C69D7353AFE1D6050A606BC61EDA13E1C3C","revision":1,"properties":[{"id":0,"value":[2,0]},{"id":1,"value":[6,0]},{"id":2,"value":[0,0]}]}}]

This is a mosaic with a divisibility of 6 and an unlimited duration
However, MosaicInfo returns a duration of 6 (and a divisibility of 6 too) using 0.12.2

**Comment by evias** [comment]
fixed in 0.12.3
