### ISSUE TITLE
Adding `aggregateTx_InnerTx.toAggregate()` for single signer

### ISSUE THREAD

**Issue by rg911** [nemtech/nem2-sdk-typescript-javascript#185]
Enhancement feature - For discussion

- Raised by Aleix on [slack](https://nem2.slack.com/archives/CEZKUE4KB/p1561386833047200)

**AggregatedCompleteTransaction**

At the moment when issuing an Aggregated Complete Transaction, `PublicAccount` is used as a mandatory parameter on `innerTx.toAggregate(..)` for every inner transactions. Catapult server will validate cosignatories if multiple accounts (signers) provided in the inner transactions to make sure the AggregateCompleteTransaction `isComplete`. There could be potentially an enhancement to be created by making this parameter `optional`. So that the ACT `Can/Only` be signed by the issuer if other signers are unknown. 

example:

```js
const transferTransaction = TransferTransaction.create(
                Deadline.create(),
                recipient.address,
                [NetworkCurrencyMosaic.createAbsolute(1)],
                PlainMessage.create('test-message'),
                NetworkType.MIJIN_TEST,
            );
const aggregateTransaction = AggregateTransaction.createComplete(Deadline.create(),
                [transferTransaction.toAggregate()],
                NetworkType.MIJIN_TEST,
                [],
            );
const signedTransaction = aggregateTransaction.signWith(issuer, generationHash);
```

- Node that the inner transaction's toAggregate method is taking zero parameter, so the only the issuer is needed to sign the ACT

**Comment by rg911** [comment]
My view of this is this enhancement is `Optional` as when construct the ACT, the `toAggregate()` method can take the issuer's Public Account, so that only the issuer is required to sign. 

```js
const transferTransaction = TransferTransaction.create(
                Deadline.create(),
                account2.address,
                [NetworkCurrencyMosaic.createAbsolute(1)],
                PlainMessage.create('test-message'),
                NetworkType.MIJIN_TEST,
            );
const aggregateTransaction = AggregateTransaction.createComplete(Deadline.create(),
                [transferTransaction.toAggregate(account.publicAccount)],
                NetworkType.MIJIN_TEST,
                [],
            );
const signedTransaction = aggregateTransaction.signWith(account, generationHash);
```

**Comment by evias** [comment]
This feature in fact **delegates signature validation to an external entity** and can be useful for application that implement aggregate transactions without knowing exactly _who will be signing_.

What can be done on the side of the SDK is to have the parameter set to be optional, and delegate the verification of "correct signer" to the broadcaster where, in case the signer is not set, the issuer is used. In those cases, transactions will most likely be passed over as payloads, and wallets intercept the payload and _fills_ it with the correct issuer public key before it get broadcast.

The `AggregateTransaction.signWith` method could stay as is and the `toAggregate` method should store `undefined` in the publicAccount field such that `signWith` will recognize and fill with issuer when needed.

**Comment by rg911** [comment]
Just to confirm that this logic only applies on `AggregateComplete` transaction!
