### ISSUE TITLE
Make KeyPair generation and SharedKey derive compatible with NIS1

### ISSUE THREAD

**Issue by rg911** [nemtech/nem2-sdk-typescript-javascript#189]
KeyPair generation and shared key derivation for encryption, used Keccak with NIS1 but catapult is using SHA3. 

To make Key generation cross-compatible from the side of the SDK, the SDK needs to allow Keccak algorithm as an option (but default to SHA3)

Catapult on public network will also be using Keccak which is why this change is important to address.

**Comment by evias** [comment]
merged in nemtech/nem2-sdk-typescript-javascript@da9f0fe
