### ISSUE TITLE
Fees and params for transfering transactions

### ISSUE THREAD

**Issue by 1nfinite** [nemtech/nem2-sdk-typescript-javascript#198]
Hello, I am new to NEM and few questions that I would like to ask.
I am expecting ethereum equivalent counterpart is
NEM token = ether
NEM mosaic token = smart contract token 

Document: [Sending a transfer transaction](https://nemtech.github.io/guides/transaction/sending-a-transfer-transaction.html)

1) Do this have a transaction fee concept? Because i didn't see any transaction fees params to be inserted for transaction. And if there is, what token does it use? I am expecting a NEM token but what i see is just merely transfering mosaic cat token without any transaction fees involved.

2) I expect that an account can hold NEM token (like Ethereum ether = NEM, token = mosaic). But i did not see any function implementation of getting NEM balance nor transfer it. Does NEM have this concept? If not, what is the usage of NEM token in this platform.

3) What value should i pass in for message if i intend to have blank message in transactions?

4) What does Deadline.create() default to and what value should i input if i intend to create a deadline of let say 24 hours.

**Comment by evias** [comment]
Hello there and welcome to NEM!

1. Catapult uses two custom mosaics by default on the network: `cat.currency` and `cat.harvest`. The one used to pay for _fees_ currently is `cat.currency`. On upcoming testnet networks it is to be expected that the mosaic will be named `nem.xem` or similar. Currently, Catapult doesn't require fees currently as mostly it is used for private blockchain networks. There is a fee parameter to transaction factory methods though.

2. To query for your account's balance you have to check the `/account/{accountId}` endpoint where you replace `{accountId}` with your account public key (or address without dashes). It will return a `mosaics` array which are your balances. Important to note is that this endpoint returns `mosaic ids`, not names, which is a bit more complicated to read through.
 
3. Message can be blank, in the sdk there is `new EmptyMessage()` to use a blank message in `TransferTransaction.create()`.

4. `public static create(deadline: number = 2, chronoUnit: ChronoUnit = ChronoUnit.HOURS)`: by default the deadline is 2 hours. You could simply do `Deadline.create(24)` to have it set to 24 hours.

:+1:

**Comment by 1nfinite** [comment]
@evias Thanks for the response.

How do we know which is `cat.currency` and which is `cat.harvest`. I am using following code to get the mosaic balance and there is 2 mosaic by default. 

I did use the id to get the mosaic detail but there is no descriptive name to indicate which is which.

```
mosaicService
    .mosaicsAmountViewFromAddress(address)
```

**Comment by rg911** [comment]
> @evias Thanks for the response.
> 
> How do we know which is `cat.currency` and which is `cat.harvest`. I am using following code to get the mosaic balance and there is 2 mosaic by default.
> 
> I did use the id to get the mosaic detail but there is no descriptive name to indicate which is which.
> 
> ```
> mosaicService
>     .mosaicsAmountViewFromAddress(address)
> ```

Hi there. 
You can instantiate a new 'MosaicId' object (`new MosaicId([481110499, 231112638])` for example, then call the `NamespaceHttp.getLinkedMosaicId(mosaicId.toHex())` should show you the name of the mosaic.

**Comment by 1nfinite** [comment]
@rg911 I am using v0.12.3. I see that getMosaicNames function accept arrays of MosaicID but it just hang there without any response nor error. Am i doing anything wrong?

const mosaicHttp = new MosaicHttp('http://localhost:3000')
let mosaicIdList = [];
let mosaicId1 = new MosaicId([481110499, 231112638]);

mosaicIdList.push(mosaicId1);

```
 mosaicHttp
        .getMosaicsNames(mosaicIdList)
        .subscribe(
            x => {
                console.log('success');
            },
            err => {
                console.log('error');
            }
        )

```

**Comment by rg911** [comment]
which server (localhost) are you using? mosaicNames are quite recent changes to the catapult rest. make sure to use the latest rest

**Comment by 1nfinite** [comment]
@rg911 so i suppose that my code is correct?

 I am using server from [https://github.com/tech-bureau/catapult-service-bootstrap](catapult-service-bootstrap). I guess the version I am using is v0.3.0 since it show that it is the last release before v0.50.1(which release a day ago)

**Comment by rg911** [comment]
makes sense now. 0.3.0 is an older version without the mosaicNames endpoint. 0.50.1 however is the first `Elephant` compatible release. There are quite a lot changes since. If you want to build you local server using the latest, please use the latest SDK (v0.13.0)
