### ISSUE TITLE
Failure_Core_Invalid_Version

### ISSUE THREAD

**Issue by 1nfinite** [nemtech/nem2-sdk-typescript-javascript#199]
I am using following cli and sdk to make transaction

nem2-cli v0.12.1: Failure_Core_Invalid_Version
nem2-sdk v0.12.13: Transaction package sent message (but cli monitor does not capture that)

Is this because I am using wrong version of server??
I am using v0.3.0 [catapult-bootstrap-service](https://github.com/tech-bureau/catapult-service-bootstrap/releases/tag/v0.3.0) from tech-bureau since it does not have v0.4.x version. But i am not sure whether it is under cow or dragon network.

**Comment by evias** [comment]
v0.3.0 is cow which means you will need SDK@v0.11.6 :+1:
