### ISSUE TITLE
New or breaking changes on 0.13 sdk

### ISSUE THREAD

**Issue by 1nfinite** [nemtech/nem2-sdk-typescript-javascript#200]
Is there any new or breaking changes on sdk 0.13 as compared to 0.12?

**Comment by rg911** [comment]
There is, 0.13 is Elephant compatible, all transaction versions have been reset

**Comment by 1nfinite** [comment]
@rg911 let me elaborate more. IS there any code changes that need to be done should we upgrade sdk to 0.13 and server to Elephant?

**Comment by evias** [comment]
breaking changes in source code introduced:

- rename of *AccountProperties* to account and mosaic restrictions

**Comment by rg911** [comment]
? Account restriction PR hasn't been merged yet ! ?
