### ISSUE TITLE
Failure to retrieve information regarding successfuly created Account

### ISSUE THREAD

**Issue by hulekal123** [nemtech/nem2-sdk-typescript-javascript#207]
Hi,

I am new to NEM Techology. For my project I am trying to user your blockchain. 
After getting basic ideas clarified with nem2-cli, I have ventured into programming using SDKs. 

**Setup :** 
Ubuntu : 18.04
Nem2CLi : 0.12.1
Docker : 18.09.7 Build : 2d0083d
DOcker-Compose : 1.21.2 Build a133471
SDK Repo : Latest

Code-Snippet
```
const account = Account.createFromPrivateKey(privateKey, NetworkType.MIJIN_TEST);
const password = new Password(user.password);
const wallet = SimpleWallet.create(user.firstName, password, NetworkType.MIJIN_TEST);
const userAccount = wallet.open(password);
 console.log('Your new account address is:', userAccount.address.pretty(), ' its private key', userAccount.privateKey, 
        'and its public key', userAccount.publicKey);
```
This snippet creates a user account and outputs all user information including Address.

Validation

Issue-1
I try to validate this user via nem2-cli giving the user address as argument. 
$ nem2-cli account info --address XX_YY_ZZ
Account:        XX_YY_ZZ
-------------------------------------------------------

Address:	XX_YY_ZZ
at height:	11018

PublicKey:	0000000000000000000000000000000000000000000000000000000000000000
at height:	0

Importance:	0
at height:	0

Mosaics
43c2851137b55a1 90

Issue-2

Also, I check profile list with nem2-cli 
$ nem2-cli profile list
Here only those accounts get displayed, which are created/generated by nem2-cli and *not the accounts created programmatically by SDKs*

Issue-3

When I try to fetch User infromation programtically too, get Public Address 0000.

What may have gone wrong ? Please suggest.

Many thanks for your time.

**Comment by rg911** [comment]
1. Expected behaviour, As newly created account doesn't have a 'valid' public key yet. Try transfer some assets see if the public key changed.
2. cli generated account stored in local env. List all account from server is not supported. expected behaviour

**Comment by hulekal123** [comment]
1. As documented in the Transfer transaction, I executed a transaction with a created mosaic "successfully". But still I do not see any Public Key :(

```
const mosaicId = '6e527b45794dd414';
       
        const transferTransaction = TransferTransaction.create(
            Deadline.create(),
            Address.createFromRawAddress(userAccount.address.pretty()),
           // [],
            [new Mosaic(new MosaicId(mosaicId), UInt64.fromUint(10000))],
           // [NetworkCurrencyMosaic.createRelative(10000)],
            PlainMessage.create('enjoy your ticket!'),
            NetworkType.MIJIN_TEST
        );
```
I am stuck at this situation, without getting public key


Here is the output from nem2-cli
nem2-cli account info --address  SA2FS3-XPLDL2-GKSDJV-IXBZLV-EQQHFM-DCVKKT-264R
Account:        SA2FS3-XPLDL2-GKSDJV-IXBZLV-EQQHFM-DCVKKT-264R
-------------------------------------------------------

Address:	SA2FS3-XPLDL2-GKSDJV-IXBZLV-EQQHFM-DCVKKT-264R
at height:	11301

PublicKey:	0000000000000000000000000000000000000000000000000000000000000000
at height:	0

Importance:	0
at height:	0

Mosaics
3a81bd6be96f9b8f:	100000

Here one can see enough assets assigned, but still Public Key is 0

2. Where are the programtically created/generated account information stored ? how can i validate ? 

Thanks in advnace.

**Comment by rg911** [comment]
Have you tried call the rest endpoint directly. e.g. `http://localhost:3000/account/{address}` see if the public key is correct there?

**Comment by hulekal123** [comment]
Unfortunately not much luck there either 

`{"meta":{},"account":{"address":"9034596EEF58D7A32A434D5170E575242072B062AA953D7B91","addressHeight":[11301,0],"publicKey":"0000000000000000000000000000000000000000000000000000000000000000","publicKeyHeight":[0,0],"accountType":0,"linkedAccountKey":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","activityBuckets":[],"mosaics":[{"id":[3916405647,981581163],"amount":[100000,0]}],"importance":[0,0],"importanceHeight":[0,0]}}`

**Comment by dgarcia360** [comment]
When the account first **receives** a transaction, its **address** is stored in the network. You can see the block where the address first appeared under ``addressHeight``.

However, at this point you can use the public key as well to query transactions:

> http://localhost:3000/account/<public_key>/transactions

When the account first **sends** a transaction, its **public key** is stored in the network. You can see the block where the public key first appeared under ``publicKeyHeight``.

**Comment by rg911** [comment]
I think issue is the publicKey shows `0000....' so you can not even call the  account transaction endpoint. @hulekal123 have you got other accounts created? Are their public keys look the same? Or perhaps call the `clear-all` script to refresh your local server (note that this will wipe out everything including your existed nemesis accounts).

**Comment by hulekal123** [comment]
Hi  @dgarcia360  
For the following setup, i was looking for Public Key
{"meta":{},"account":{"address":"9034596EEF58D7A32A434D5170E575242072B062AA953D7B91","addressHeight":[11301,0],"publicKey":"0000000000000000000000000000000000000000000000000000000000000000","publicKeyHeight":[0,0],"accountType":0,"linkedAccountKey":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","activityBuckets":[],"mosaics":[{"id":[3916405647,981581163],"amount":[100000,0]}],"importance":[0,0],"importanceHeight":[0,0]}}

and the http://localhost:3000/block/11301   (#11301 is the Addressheight) returns following o/p. Here too i see lot of 00000
{"meta":{"hash":"338C18F834D5FF7C2AEFD7AD0359541AD2036F16BC3D9FC77EAA4220EC74DD30","generationHash":"B93372CB292EDD3CD588EB01E78D73C600F150E38BD0967507F637A01B484AB2","totalFee":[0,0],"subCacheMerkleRoots":["10A8529ABC2B5B76F59408797D1891521A441D9DF4F6528DD7EA2EDFE02CBCC6","F43DE1D5A235696518B4DB39455AD0BC4BF5DAF7EB0DF6CBBADCD90CF9B5CEEB","07803B546544910D4CA59DA8406C5ED0CEFEDE0C5A5362F959F2FA93C5C904C3","0000000000000000000000000000000000000000000000000000000000000000","0000000000000000000000000000000000000000000000000000000000000000","0000000000000000000000000000000000000000000000000000000000000000","0000000000000000000000000000000000000000000000000000000000000000"],"numTransactions":1,"numStatements":1},"block":{"signature":"F1ACE8F3D602E8B06874DF954B8F08F2981F84FA16BF8760F6F05D24C7F48EC069844FB5CB8045EDE47B8747CFA06D1D1D2206F654FC6D4BC90E0043DD955E0D","signer":"269CEFE82A312E3C7A97E070D0408EAF6183A241D6B1210681A9473C6751B6AD","version":36867,"type":33091,"height":[11301,0],"timestamp":[983501284,24],"difficulty":[2606025390,10451],"feeMultiplier":0,"previousBlockHash":"4D9B751D44171BBE0190BD38257F572AC55C5E298133AF38DD23A796EC24399B","blockTransactionsHash":"100824361469624F76FA0A0018DC5D0E65C7966FD47E5123B977A39A81A38DC3","blockReceiptsHash":"5763957600328E45961CB06A49C153FC76BA7DDCD8A73536A164667FD386BB54","stateHash":"630087E5E2BA01C2A4EC6654A13B939891FA9386EB018351E1B0269FA0755CD3","beneficiary":"0000000000000000000000000000000000000000000000000000000000000000"}}

**Comment by hulekal123** [comment]
I tried clean-all method too.

UNfortunately I get public key still 0000. 
ALso how can i retrieve private key of an account ? is there any reverse look up method ?

THanks

**Comment by vazudew** [comment]
I tried on a clean VM with a fresh setup and with nem2-cli, following tasks to verify @hulekal123 observations

**Tasks and Comments**
1) creation of default profile, with generated private key => SUCCESS
2) generation of another account X => SUCCESS
 (`$ nem2-cli account generate --network MIJIN_TEST -s --url http://localhost:3000 --profile X`)
3) `$ nem2-cli profile list ` # lists both default and X Accounts with Public and Private keys => SUCCESS
4)  `$ nem2-cli account info --address default_ADDRESS`  or  `$ nem2-cli account info --profile default` 
=> SUCCESS with dispay of Mosaics, FAIL : but Public Key is 000000...
5) `$ nem2-cli account info --address X_ADDRESS`  or  `$ nem2-cli account info --profile X` => FAIL , Error 404
6) transfered some mosaics into X account => SUCCESS, generated hash DEF_X_HASH
`nem2-cli transaction transfer --recipient X_ADDDRESS --message "payout of 10 xem" --mosaics @cat.currency::10000000 `
7) `nem2-cli transaction info --hash  DEF_X_HASH`  #no useful Address or Keys of either default or X account 
8) `$ nem2-cli account info --address X_ADDRESS`  or  `$ nem2-cli account info --profile X` => SUCCESS with dispay of Mosaics, FAIL : but Public Key is 000000...
9) tested on browser following Endpoints
a) http://localhost:3000/account/{PublicKey}/ or http://localhost:3000/account/{PublicKey}/transactions => Public Key always displayed 0000
b) http://localhost:3000/block/{addressHeight} or http://localhost:3000/block/{publicKeyHeight} => Public Key either not mentioned or always displayed 0000

**Conclusion**:
So I guess the Public Key is always displayed to be 0000 :-/ However, $ nem2-cli profile list always displays both Public and Private Key

**Question** 
After a successful transfer transaction of Mosaics from Default account to another account X, a Hash and SIgner information are generated. But how can one confirm the Sender and Recipient of transactions ? 
Technically how can prove participation of certain account holders without having Public Key or Address displayed ?
