### ISSUE TITLE
unable to use nem2-sdk in StackBlitz

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#209]
**1. Expected behavior and actual behavior.**
StackBlitz is a popular online IDE that supports the installation of npm libraries. We'd like to use it to facilitate virtual environments to students without having to download the SDK locally.

The IDE currently complains about a dependency: 

```
Import error, can't find file:
./zlib_bindings
```
**2. Steps to reproduce the problem.**

Create an RxJs + TS StackBlitz project, import nem2-sdk and use it.

**Demo project:** https://stackblitz.com/edit/rxjs-hkd1yj

**3. Specifications like the version of the project, operating system, or hardware.**

nem2-sdk@0.13.0

**Comment by rg911** [comment]
Never used `stackblitz` not sure what version of node it's using. 
However, tried on `codesandbox` with same dummy code, seems working fine 

https://codesandbox.io/s/silly-euclid-zw75c

**Comment by rg911** [comment]
shall we close this issue?
