### ISSUE TITLE
MosaicId test not throwing on namespaceIds

### ISSUE THREAD

**Issue by decentraliser** [nemtech/nem2-sdk-typescript-javascript#217]
This test is validating a `namespaceId`

I want to use the SDK for string validation purposes.
Here, I want to validate a mosaicId input by putting `new MosaicId(mosaicIdToTest)` in a Try Catch.

It would be nice that `new MosaicId(namespaceId)` throws an error for this use case.

**Comment by rg911** [comment]
SDK won't be able to validate mosaicId against namespaceId at the format of both is Uint64 (number[]). I also don't think SDK should be responsible for the validation as
a. validation should falls into implementation client layer's responsibility
b. any txs with invalid Ids will get rejected by the server validator. 

However, there are http clients you can call e.g. the `mosaicHttp` `namespaceHttp` for your validation purposes.

**Comment by decentraliser** [comment]
OK, thanks!
I am trying to reduce http clients to improve performance, that's why I'm looking for that kind of methods
