### ISSUE TITLE
Account transaction encrypted message missing recipientPublicAccount

### ISSUE THREAD

**Issue by kahwooi** [nemtech/nem2-sdk-typescript-javascript#219]
1. Expected behavior and actual behavior.

    I am expecting `recipient public key` when getting transaction from an account

2. Steps to reproduce the problem.

```
const accountHttp = new AccountHttp('http://localhost:3000');
accountHttp.transactions(publicAccount, new QueryParams(pageSize))
    .subscribe((transactions) => {
         console.log(transactions[0]) // How to get the recipient public key
    }, (err) =>  {
            console.error(err)
   })
```
   The log `console.log(transactions[0])` give me `undefined `recipientPublicAccount: 

```
...
message:
   EncryptedMessage {
     type: 1,
     payload:
      'C916D73150546...',
     recipientPublicAccount: undefined }
```

   Can I get the recipient public account, so that I can decrypt the message. 

3. Specifications like the version of the project, operating system, or hardware.

     I am using Dragon Network and nem2-sdk: 0.13.0

**Comment by rg911** [comment]
For me I don't think we should even return the `recipientPublicAccount` at all for security reason. 
@evias what do you think?

We can probably use the abstract class - `Message` which should only have the `type` and `payload`

**Comment by kahwooi** [comment]
Is there anyway I can get the `recipientPublicAccount`, because I need to decrypt the message using signer account?

**Comment by rg911** [comment]
The publicKey is the same key you used on encryption

**Comment by kahwooi** [comment]
Yes, but I didn't save the recipient public keys after using it to decrypt message. I cannot get the public key from the recipient address.

**Comment by rg911** [comment]
Don't think you can get generate the the publicKey from Address using the SDK. Address is generated from KeyPair in one way.

**Comment by evias** [comment]
when you encrypt a message, this is fully on the client side now.

So it means you have to encrypt with **sender private key** _concatenated_ with **recipient public key** as to create a **shared keypair**.

To decrypt its the other way around, the shared keypair will be **recipient private key** _concatenated_ with **sender public key**.

I suspect that the currently available `EncryptedMessage` class does not function correctly.

**Comment by rg911** [comment]
> when you encrypt a message, this is fully on the client side now.
> 
> So it means you have to encrypt with **sender private key** _concatenated_ with **recipient public key** as to create a **shared keypair**.
> 
> To decrypt its the other way around, the shared keypair will be **recipient private key** _concatenated_ with **sender public key**.
> 
> I suspect that the currently available `EncryptedMessage` class does not function correctly.

I think the encryption function works fine. The problem I can see here reading @kahwooi 's input
- When we send the encrypted message with Transfer, message does not have the `recipientPublicKey`. (currently only the `type (= 1)`, and the `payload`.
- When calling the `createTransactionFromDto(transfer)`, when creating the `EncryptedMessage` instance, the `recipientPublicKey` get left `undefined` as it is not in the dto payload.

**Comment by kahwooi** [comment]
Yes, my question is where can I get the recipient public key from Transaction object when I use     accountHttp.transactions to query the transactions of the account?

**Comment by rg911** [comment]
I think we can probably close this ticket now. 
For recipient to decrypt message it needs:
1. Recipient's private key - recipient must have it already
2. Sender's publicKey - which is the `signer` of the transaction. 

@kahwooi @evias  ?
