### ISSUE TITLE
unable to get websocket errors

### ISSUE THREAD

**Issue by jorisadri** [nemtech/nem2-sdk-typescript-javascript#22]
When opening the listener and connecting to a wrong url, an error is expected. 
Currently only a log is thrown in the console. 

To reproduce the behaviour try to connect the listener to a server that does not host a catapult server.

Using javascript and nem2-sdk-typescript-javascript

**Comment by dgarcia360** [comment]
More information:  The error is console logged, but [there is no error thrown](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/infrastructure/Listener.ts#L104).

**Comment by baskaranc** [comment]
Had similar issue, seems only one container started
Check all the 5 containers are running if not clean the data and start again 
`./clean-data`
and start the `docker-compose up -d`

`catapult-service-bootstrap_api-node-0`
`catapult-service-bootstrap_peer-node-1`
`techbureau/catapult-rest-server:1.0.7`
`catapult-service-bootstrap_peer-node-0`
`mongo`

**Comment by jorisadri** [comment]
I think the issue you descibe is something different than this issue

**Comment by evias** [comment]
Fixed in PR #63
