### ISSUE TITLE
modificationType instead of restrictionType

### ISSUE THREAD

**Issue by decentraliser** [nemtech/nem2-sdk-typescript-javascript#220]
https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/4d22d6fec1e4e722849b19480b843e8bd08f85be/src/model/transaction/AccountRestrictionModification.ts#L26

I think it should be `restrictionType` instead of `modificationType` here.

I'm testing on Elephant 2, `MODIFY_ACCOUNT_RESTRICTION_ADDRESS` transaction

Transaction returned by the SDK
![image](https://user-images.githubusercontent.com/36499647/62410476-a24df880-b618-11e9-9466-e5fa016ba950.png)

Transaction returned by the API
![image](https://user-images.githubusercontent.com/36499647/62410482-c01b5d80-b618-11e9-9ad7-9a12dff67f7c.png)

**Comment by decentraliser** [comment]
Same comment for mosaics:
![image](https://user-images.githubusercontent.com/36499647/62505907-09de9080-b831-11e9-9f5f-7dc8f1eaee48.png)
****
![image](https://user-images.githubusercontent.com/36499647/62505926-27135f00-b831-11e9-9082-4d3295e70756.png)

**Comment by rg911** [comment]
- was this returned from ws listener or rest api calls?
- which env you were using?

I am working on it right now anyway

**Comment by decentraliser** [comment]
Using accountHttp on C2

**Comment by rg911** [comment]
> Using accountHttp on C2

try use local bootstrap, rest on c2 is not up to date

**Comment by rg911** [comment]
confirmed this is rest issue, I will report 👍

**Comment by rg911** [comment]
Going to close this one as issue reported to the rest team.

https://github.com/nemtech/catapult-rest/issues/69

Thanks very much for reporting 👍

**Comment by decentraliser** [comment]
cool! my pleasure!

Jean-Luc
