### ISSUE TITLE
Address plain or encoded in AccountRestrictionModification value field

### ISSUE THREAD

**Issue by decentraliser** [nemtech/nem2-sdk-typescript-javascript#221]
https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/4d22d6fec1e4e722849b19480b843e8bd08f85be/src/model/transaction/AccountRestrictionModification.ts#L44

When creating an `AccountAddressRestrictionModificationTransaction`, `AccountRestrictionModification.value` is a plain address.

When retrieving (`accountHttp.transactions`) an  `AccountAddressRestrictionModificationTransaction`,
`AccountRestrictionModification.value` is an encoded address.

I think it would be better to keep a consistent address format in this interface if possible

**Comment by rg911** [comment]
Don't think this is an issue here, `Address` object can be initiated by calling `Address.createFromEncoded()` which the sdk handles all inbound address payload elsewhere.

**Comment by decentraliser** [comment]
I agree with that, it is not really an issue to get the formatted address

However, it is still an extra logical step on the client side, for handling
a single interface
Jean-Luc

**Comment by rg911** [comment]
Not `formatted` but it's strong typed. And there's a strong typed consistency across this sdk project like other object initiation and transaction builders (transferTx e.g). I can't see a strong point to break this consistency?

**Comment by decentraliser** [comment]
Right, it makes sense with this point of view. 
I'm just thinking that it might confuse developers, but it is not a big problem
