### ISSUE TITLE
[Elephant 3] Apply latest DTO and API client from nem2-docs

### ISSUE THREAD

**Issue by rg911** [nemtech/nem2-sdk-typescript-javascript#223]
Apply latest DTO and API client from nem2-docs

**Comment by dgarcia360** [comment]
Before applying this change, please wait until https://github.com/nemtech/nem2-docs/issues/223 is applied. Also, it will be ideal to investigate how to resolve the "anyOf" issue - or skip the affected properties.

**Comment by dgarcia360** [comment]
New swagger spec: https://github.com/nemtech/nem2-openapi
