### ISSUE TITLE
Questions in get partial aggregate bonded transactions and remove the only cosigner from cosignatories list

### ISSUE THREAD

**Issue by domakun** [nemtech/nem2-sdk-typescript-javascript#225]
**1. An empty array was returned after  the request of partial aggregate bonded transactions**
In sdk v13.0.0 , `AccountHttp.aggregateBondedTransactions()` seems not work , I test the url '.../account/{publicKey}/transactions/partial' ,it also returns null array .
 The comment in code shows that the method AccountHttp.aggregateBondedTransactions() and the url '.../account/{publicKey}/transactions/partial'  show returns partial transactions.

**2.The only cosigner in cosignatories list can not remove itself to turn a multisig  account into a normal account** 
It's OK while 2 or more cosigners in cosignatories list, but the problems occured while the last cosigner want to remove itself from cosignatories list, the node return `Failure_Multisig_Modify_Min_Setting_Out_Of_Range`  error.

**Comment by evias** [comment]
1. @rg911 please verify if this is maybe a REST problem then tag roger ?

2. @BloodyRookie @Jaguar0625 @gimer

**Comment by rg911** [comment]
1. I don't see the partial transactions neither, will report to rest to have a look. @Vektrat
