### ISSUE TITLE
MosaicHttp.getMosaicNames broken

### ISSUE THREAD

**Issue by decentraliser** [nemtech/nem2-sdk-typescript-javascript#228]
1. Expected behavior and actual behavior.
`MosaicHttp.getMosaicNames `not to throw (cannot read property map of undefined)

2. Steps to reproduce the problem.
`MosaicHttp.getMosaicsNames(cat.currenty mosaicId)`

3. Specifications like the version of the project, operating system, or hardware.
latest tech-bureau/catapult-server-bootstrap, latest testnet

description:

It seems to be an issue with `MosaicNamesDTO`, below is the console log of "mosaics" in the quoted line

https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/71e41cde6afec5dc82522ea2f86516dd06cbe54a/src/infrastructure/MosaicHttp.ts#L160
![image](https://user-images.githubusercontent.com/36499647/62747049-2b37ba80-ba85-11e9-9f45-1fa122dffb28.png)

**Comment by evias** [comment]
can you test whether http://localhost:3000/mosaic/{mosaicId} returns correct information ?

**Comment by decentraliser** [comment]
here is the output of http://localhost:3000/mosaic/{mosaicId} @evias 
![image](https://user-images.githubusercontent.com/36499647/62905970-5aa93880-bd9f-11e9-9148-b251dbdff9d1.png)

**Comment by rg911** [comment]
MosaicHttp is not working properly due to schema update on rest. 
https://github.com/nemtech/catapult-rest/issues/72

**Comment by decentraliser** [comment]
Hi! Any plan about this issue? I see that the nemtech/catapult-rest#72 was merged
