### ISSUE TITLE
getTransactionStatus fails when querying for failed transactions

### ISSUE THREAD

**Issue by jorisadri** [nemtech/nem2-sdk-typescript-javascript#24]
When querying for transaction status and the transaction failed. The <a href="https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/infrastructure/TransactionHttp.ts#L96">height</a> is not provided by the api but it is expected in the SDK

**Comment by jorisadri** [comment]
Sorry I was wrong, it does not fail when the height is not provided.

**Comment by rg911** [comment]
https://github.com/nemtech/nem2-sdk-typescript-javascript/pull/59
Fixed, unit test to be added after nem2-lib decommissioned.

**Comment by evias** [comment]
Fixed with PR #59
