### ISSUE TITLE
mosaicId not correctly instanciated in MosaicAlias

### ISSUE THREAD

**Issue by decentraliser** [nemtech/nem2-sdk-typescript-javascript#246]
```
const namespaces = await namespaceHttp.getNamespacesFromAccount(address).toPromise()
namespaces.forEach(namespace =>{
   if (namespace.namespaceInfo.alias instanceof MosaicAlias) {
       console.log(alias.toHex(namespace.namespaceInfo.alias))
       console.log(alias.toHex(namespace.namespaceInfo.alias.toHex()))
  }  
}

```
![image](https://user-images.githubusercontent.com/36499647/64525760-2429f380-d334-11e9-99bf-dba61e6e93fa.png)

having `this.mosaicId = new MosaicId(mosaicId);` in the constructor does the trick, but I doubt this is the root cause.

https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/c15999ab8dbb602ffe2332e4b51ba1b99b2774de/src/model/namespace/MosaicAlias.ts#L59

**Comment by rg911** [comment]
@decentraliser do you still have the same issue after E3 schema changes patched?

**Comment by decentraliser** [comment]
not sure yet, will update you when I have a chance to try it

**Comment by rg911** [comment]
@decentraliser does this error still present?

**Comment by decentraliser** [comment]
yes, still there
