### ISSUE TITLE
recipientAddress variable name confusing?

### ISSUE THREAD

**Issue by decentraliser** [nemtech/nem2-sdk-typescript-javascript#263]
I'm not sure about the name of `recipientAddress` property since it can be whether an Address or a NamespaceId

https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/181fe8601ebc24d27f7c5df7b0149853812798ab/src/model/transaction/TransferTransaction.ts#L62

**Comment by rg911** [comment]
RecipientAddress to match catabuffer schema. It can be `Address` | ‘AddressAlias` as taken by transfer transaction.

**Comment by dgarcia360** [comment]
NamespaceId in this case is acting as an ``UnresolvedAddress``.

**Comment by decentraliser** [comment]
Yes I get the point, but still think that `recipient` makes more sense, because an AddressAlias is not an address

**Comment by rg911** [comment]
@decentraliser I am for @dgarcia360 's point plus we already discussed this before implementation. Shall we keep the name for now and if it really cause confusion to the wider group we can definitely change it since it's only a small change.
