### ISSUE TITLE
MosaicDTO flags are undefined

### ISSUE THREAD

**Issue by decentraliser** [nemtech/nem2-sdk-typescript-javascript#265]
on E3

![image](https://user-images.githubusercontent.com/36499647/65403306-89d2b100-de05-11e9-9142-f4649b7a83b8.png)

**Comment by decentraliser** [comment]
seems I'm not testing on the latest REST

**Comment by decentraliser** [comment]
still true with `^0.13.3`

**Comment by Vektrat** [comment]
https://github.com/nemtech/catapult-rest/issues/151
