### ISSUE TITLE
cosignatory ws channel not working

### ISSUE THREAD

**Issue by yaaccount** [nemtech/nem2-sdk-typescript-javascript#267]
Hi! I've identified this line to be reason why cosignatory websocket notification is never called correctly: 

https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/7952d248fe330118e8fed037f94e3eb1554e602b/src/infrastructure/Listener.ts#L154

... adding "&& message.meta.hash" to the condition solves the issue.

(this is against xpx servers, may not be relevant for nem, but IMO it is)

**Comment by rg911** [comment]
Good spot but don't think this is the root cause. IMO, the https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/7952d248fe330118e8fed037f94e3eb1554e602b/src/infrastructure/Listener.ts#L156 should come before the `message.meta` elseif
