### ISSUE TITLE
TransferTransaction always return PlainMessage with type = 0

### ISSUE THREAD

**Issue by thomas-tran** [nemtech/nem2-sdk-typescript-javascript#27]
1. Expected behavior and actual behavior.
Expected behaviour: TransferTransaction return message with type = 1 for plain message
Actual behaviour: TransferTransaction return message with type = 0 for plain message
2. Steps to reproduce the problem.
transactionHttp.getTransaction(transactionHash);

Is it possible to have the Encrypted Message and PlainMessage like NIS 1?

**Comment by evias** [comment]
I don't think this is possible in the current version of catapult.

Regarding the type field, this documentation seems to imply `0` as being correct for the type of message: https://nemtech.github.io/concepts/transfer-transaction.html
