### ISSUE TITLE
MosaicGlobalRestrictionTransaction.create() parameter error.

### ISSUE THREAD

**Issue by ivyfung1** [nemtech/nem2-sdk-typescript-javascript#270]
MosaicGlobalRestrictionTransaction.create()

     * @param deadline - The deadline to include the transaction.
     * @param mosaicId - The mosaic id ex: new MosaicId([481110499, 231112638]).
     * @param referenceMosaicId - The mosaic id providing the restriction key.
     * @param restrictionKey - The restriction key.
     * @param previousRestrictionValue - The previous restriction value.
     * @param previousRestrictionType - The previous restriction type.
     * @param newRestrictionValue - The new restriction value.
    ` * @param previousRestrictionType - The previous restriction tpye.`
     * @param networkType - The network type.
     * @param maxFee - (Optional) Max fee defined by the sender
     * @returns {MosaicGlobalRestrictionTransaction}

The second `* @param previousRestrictionType - The previous restriction tpye.` shall be  `* @param newRestrictionType - The new restriction tpye.` I think that's a typo.

**Comment by Vektrat** [comment]
thanks for reporting this issue here
