### ISSUE TITLE
createFromEncoded not in Address.d.ts

### ISSUE THREAD

**Issue by decentraliser** [nemtech/nem2-sdk-typescript-javascript#273]
not sure if the @internal is the cause, but it would be nice to have it in the d.ts 

https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/9e3f83f169dfda07ae8f63e0f3727b75c560c7cf/src/model/account/Address.ts#L67

**Comment by rg911** [comment]
It is, so internal will hide it in the definition files. will make it publick
