### ISSUE TITLE
Cannot create MosaicGlobalRestriction with referenceMosaicId

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#275]
**1. Expected behavior and actual behavior.**

I'm having problems when creating a mosaic global restriction with a ``referenceMosaicId``, getting the error ``Failure_RestrictionMosaic_Previous_Value_Must_Be_Zero`` (see **2. Steps to reproduce the problem**).

The issue might not be in the SDK, but in the catbuffer serialization or server. Please feel free to escalate the issue to another repo if someone finds the root of the problem. Even though, we could start by adding an e2e test.

**2. Steps to reproduce the problem.**

Assuming  key = randUInt64Value

1. Create a new restrictable mosaic M1 with account A
2. Announce with A a MosaicGlobalRestriction TX1:

| Property | Value |
| - | - |
|**mosaicId** | M1 | 
|**restrictionKey** |  key  | 
|**previousRestrictionType** | None  | 
|**previousRestrictionValue** | 0  | 
|**newRestrictionType** | EQ  | 
|**newRestrictionValue** | 1  | 

3. TX1 gets confirmed
4. Create a new restrictable M2 mosaic M2  with account B
5. Announce with B a MosaicGlobalRestriction TX2

| Property | Value |
| - | - |
| **mosaicId** | M2 | 
| **referenceMosaicId** | M1 |
| **restrictionKey** |  key |
| **previousRestrictionType** | None |
| **previousRestrictionValue** | 0 |
| **newRestrictionType** | EQ |
| **newRestrictionValue** | 2 |

6. TX2 does not get confirmed, raising the error ``0x80510003 - Failure_RestrictionMosaic_Previous_Value_Must_Be_Zero``

You can also find here the [code used](https://nemtech.github.io/guides/restriction/delegating-mosaic-restrictions-to-a-third-party.html#background) (steps 1-3).

3. Specifications like the version of the project, operating system, or hardware.

* nem2-sdk@0.13.3
* c2 0.7.0.1

**Comment by rg911** [comment]
Tested got the same error here. 
Tried announced 2 global restriction transactions here 

- ReferenceMosaic (M1) -- successfully announced
```
      MosaicId: M1
      Key: UInt64.fromUint(60641),
      PrevValue: UInt64.fromUint(0),
      PrevType: MosaicRestrictionType.NONE,
      NewValue: UInt64.fromUint(0),
      NewType: MosaicRestrictionType.GE,
```

- Another Mosaic (M2) -- Error `Failure_RestrictionMosaic_Previous_Value_Must_Be_Zero` 
```
      MosaicId: M2
      Key: UInt64.fromUint(60641),
      PrevValue: UInt64.fromUint(0),
      PrevType: MosaicRestrictionType.NONE,
      NewValue: UInt64.fromUint(1),
      NewType: MosaicRestrictionType.GE,
      ReferenceMosaicId: M1
```
@dgarcia360 @Jaguar0625

**Comment by rg911** [comment]
under investigation by core
