### ISSUE TITLE
(Request new feature) Listener for cosignatories -> Listener.multisigAccountAdded()

### ISSUE THREAD

**Issue by aizaiz** [nemtech/nem2-sdk-typescript-javascript#28]
Right now I could use Listener to listen on Multisig Account address if I want to do ModifyMultisigAccountTransaction. But I think we need the cosignatories to be able to listen to ModifyMultisigAccountTransaction as well, so cosignatories can get notification if he becomes cosignatories of some Multisig Account.

So I suggest a new feature for cosignatories to be able to listen to ModifyMultisigAccountTransaction.
We could add one more feature to Listener. maybe we can call it multisigAccountAdded.

so it will be like Listener.multisigAccountAdded()

**Comment by evias** [comment]
merged in master

will be integrated in later to be published v0.11.2
