### ISSUE TITLE
blockHttp.getBlockByHeight() height should be a UInt64 value

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#280]
[blockHttp.getBlockByHeight(height)](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/1d7a18b/src/infrastructure/BlockRepository.ts#L36) takes a ``number`` as a parameter. 

When a chain height exceeds the maximum ``number`` representation, this function will not be usable. To solve this, we could change the SDK function to ask for a UInt64 value.

**Comment by rg911** [comment]
SDK can/certainly change to use UInt64, but the lower level API handler is still using number. I feel like `Rest` also needs changing to adopt this?

@Vektrat @martinayora

**Comment by Vektrat** [comment]
if we change this we should probably review the whole project, because height appears in many urls - and for consistency, maybe request data as well?

**Comment by Vektrat** [comment]
of course, but before planning it we should solve the questions raised here ;p
