### ISSUE TITLE
errorHandling when 404 from getAccountInfo

### ISSUE THREAD

**Issue by decentraliser** [nemtech/nem2-sdk-typescript-javascript#285]
all latest

When hitting `accountHttp.getAccountInfo`, for an unknown account, the error is thrown badly because the error is not within `body`, and it doesn't get stringified

![image](https://user-images.githubusercontent.com/36499647/66249491-0f8c2000-e767-11e9-8dd2-95a5e65c1072.png)

![image](https://user-images.githubusercontent.com/36499647/66249509-42ceaf00-e767-11e9-908e-61ce90015a01.png)

https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/71e41cde6afec5dc82522ea2f86516dd06cbe54a/src/infrastructure/Http.ts#L61

**Comment by 44uk** [comment]
I met inconvenience error when account is not found.

```
Error: [object Object]
```

<img width="408" alt="スクリーンショット_2019-10-05_14_34_29" src="https://user-images.githubusercontent.com/370508/66250413-5f75e180-e77d-11e9-9a1f-389e946e42b6.png">

<img width="449" alt="スクリーンショット_2019-10-05_14_38_35" src="https://user-images.githubusercontent.com/370508/66250454-e5922800-e77d-11e9-8fe0-27ba488d9f0f.png">
