### ISSUE TITLE
NetworkHttp only allow MIJIN_TEST type

### ISSUE THREAD

**Issue by rg911** [nemtech/nem2-sdk-typescript-javascript#287]
Only the MIJIN Test network type is allowed in the ` NetworkHttp.getNetworkType` which seems wrong

**Comment by rg911** [comment]
@dgarcia360 @evias

**Comment by dgarcia360** [comment]
The endpoint ``/network ``returns the info available in the [rest configuration file](https://github.com/nemtech/catapult-rest/blob/ac7c74f7b293ef554bcc3687cb46256f17f84aad/rest/resources/rest.json#L2). Although every node/network could change this value, the former SDK devs decided to parse ``mijinTest`` to ``NetworkType.MIJIN_TEST``. However, this configuration file could contain any invalid value, so it might be time to change how we get the network type.

As a potential solution, ``NetworkHttp.getNetworkType()`` could parse the ``version`` property from the first block header.

[Read more](https://nemtech.github.io/concepts/block.html#blockheader) on how block header's ``version`` property is read.

**Comment by rg911** [comment]
Discussed with @evias , We decided to use `Node/info` endpoint's `networkIdentifier` instead
