### ISSUE TITLE
Metadata and Mosaic Restriction transactions do not support aliased mosaics

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#295]
The serialization schemas define that the next fields can be aliased.

* https://github.com/nemtech/catbuffer/blob/master/schemas/metadata/mosaic_metadata.cats#L12
* https://github.com/nemtech/catbuffer/blob/master/schemas/restriction_mosaic/mosaic_address_restriction.cats#L6
* https://github.com/nemtech/catbuffer/blob/master/schemas/restriction_mosaic/mosaic_global_restriction.cats#L7-10

The NEM2-SDK should accept ``NamespaceId`` for these fields as well as the current ``MosaicId`` type.

**Comment by rg911** [comment]
@Vektrat @martinayora 
Does rest support query namespaceId on above endpoints?

**Comment by Vektrat** [comment]
> @Vektrat @martinayora
> Does rest support query namespaceId on above endpoints?

what endpoints? david is talking about transactions here, i believe we are talking about announcing transactions?

**Comment by rg911** [comment]
> > @Vektrat @martinayora
> > Does rest support query namespaceId on above endpoints?
> 
> what endpoints? david is talking about transactions here, i believe we are talking about announcing transactions?

get mosaicRestriction for example. should it be allow to use namespaceId?

**Comment by Vektrat** [comment]
i'm not sure, depends on whether the mongodb collection is a mosaicId as stated, or if it can be both, which i doubt - but i still think david is talking about transactions, not endpoints

**Comment by dgarcia360** [comment]
Yes, I'm referring to transactions at the moment. 

The endpoints contract does not have to change, as you can look up for the resolution with another endpoint. However, we might indicate in the open-api spec if the state stores the mosaic resolved (MosaicId) or not (NamespaceId). We can confirm the latest once we try to send a transaction using an aliased mosaic.

**Comment by Vektrat** [comment]
since both mosaicId and namespaceId are uint64, obviously both fields are supported and forwarded to core **in transactions**
