### ISSUE TITLE
account sign method allow binary data to be signed

### ISSUE THREAD

**Issue by aleixmorgadas** [nemtech/nem2-sdk-typescript-javascript#3]
In the [Apostille Library NIP proposal](https://github.com/nemtech/NIP/issues/2), we found that `nem2-sdk` does not allow sign raw data.

we should add to `Account` class the next method:

```typescript
class Account {
    // ...
    public signRaw(data:BinaryData | string): SignedBinary;
}
```

**Comment by gimyboya** [comment]
if i am not mistaken (please correct me if i am wrong @aleixmorgadas ) the `nem-sdk` [implementation](https://github.com/QuantumMechanics/NEM-sdk/blob/master/src/crypto/keyPair.js#L39) of the sign function accepts the following types:

- BinaryKey
- Uint8Array
- string

it would be great to support all these types with `signRaw()` for `nem2-sdk`

**Comment by aleixmorgadas** [comment]
Seems like `BinaryKey` is the same as `Uint8Array`, isn't it?

**Comment by gimyboya** [comment]
No idea about that, sorry.

**Comment by gimyboya** [comment]
@aleixmorgadas does this mean that we should create an interface for `BinaryData` ? 

if so can you please share what you have in mind i am interested to do this

**Comment by aleixmorgadas** [comment]
```typescript
type SignedData = Uint8Array;

public signRaw(data: Uint8Array | string): SignedData {
    // ...
}
```

In the function, handle the type, if it's string, convert it to Uint8Array and then apply the signature method. Maybe you should add a new method called `verify signature`

**Comment by aleixmorgadas** [comment]
https://github.com/nemtech/nem2-sdk-typescript-javascript/pull/14

@gimyboya , when this PR is accepted, you will have the method `signData` in `Account` class

**Comment by gimyboya** [comment]
Thanks @aleixmorgadas i have added 'Unit8Array` support here #15
Also i think we need to support `WordArray` from `crypto-js` library which is different from `Unit8Array`
