### ISSUE TITLE
curl block with error.

### ISSUE THREAD

**Issue by mxito3** [nemtech/nem2-sdk-typescript-javascript#30]
![image](https://user-images.githubusercontent.com/25946298/49066126-1d296d00-f25b-11e8-9940-6506a1f85f27.png)

is this normal? why after 'curl localhost:3000/block/1' i got 'curl: (56) Recv failure: Connection reset by peer' error

**Comment by Vektrat** [comment]
I don't know what your issue is, but have you edited any files in Windows or are you trying to run this into a Windows similar environment? It is possible you're having errors because of file ending formats from what I see in the log

**Comment by mxito3** [comment]
i edit nothing.first i think is docker run on ipv6 cause this question.but now i change it to ipv4.the question  still not solved.so i think there is something wrong inner container.

**Comment by mxito3** [comment]
> I don't know what your issue is, but have you edited any files in Windows or are you trying to run this into a Windows similar environment? It is possible you're having errors because of file ending formats from what I see in the log

i am on Ubuntu 16.04

**Comment by Vektrat** [comment]
did you manage to get around this issue?

**Comment by mxito3** [comment]
@Vektrat i resolved this by use nem1.
