### ISSUE TITLE
The same private key is generated differently public keys and addresses in c++ code and nem2-sdk-typescript-javascript while in NetworkType.MAIN_NET.

### ISSUE THREAD

**Issue by NemTechCN** [nemtech/nem2-sdk-typescript-javascript#305]
The same private key is generated differently public keys and addresses in c++ code and nem2-sdk-typescript-javascript while in NetworkType.MAIN_NET.
1. c++ 
  private: B5ABA5C86CC4D43BC0FA39482D073A31C2DD4A8CD8934351541AFED2125A1492
  public: 958FD173E0B7C57007E5FA107530629DDEEE56784D9A3771FCD37F694D8760D7
  address: ND5B2OB5EB5PEQDRBAXWGTP3XLI26L4CB37YFPZF
2. nem2-sdk-typescript-javascript
  private: B5ABA5C86CC4D43BC0FA39482D073A31C2DD4A8CD8934351541AFED2125A1492
  public:  5C92C3221232BA58E80D695CE8DE92D163304E55CB1C0BE61EF321F07C345A3D
  address: NAC73Q3YTKBEZHGAIASYXV3IPKZJJVRZO4WMLYGV

**Comment by rg911** [comment]
This is probably because the `private key reverse` has been scrapped SDK based on server E.3 changes.  Wait and see what core responses on slack sig-api channel.

**Comment by rg911** [comment]
I think we can close this now as per Gimre and Nate's comments on slack
