### ISSUE TITLE
The function "signWith" does not find in Transaction.d.ts

### ISSUE THREAD

**Issue by kz3** [nemtech/nem2-sdk-typescript-javascript#312]
I'm not sure but it seems the definition of the function "signWith" is not in Transaction.d.ts, because of the **@internal** below. Dose it should be **@public** ?
https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/819fcfe4dd5600ca5b30d22291a19b17436ae2f0/src/model/transaction/Transaction.ts#L117

**Comment by rg911** [comment]
signeWith is internal as per design. Public method is in `Account`. use account.sign...

**Comment by kz3** [comment]
@rg911 
I see, I will use `Account` method. Thanks a lot!
