### ISSUE TITLE
The function 'getAccountMetadata' can't get account metadata.

### ISSUE THREAD

**Issue by keita1484** [nemtech/nem2-sdk-typescript-javascript#321]
I got an empty response when the `getAccountMetadata()` parameter is address.

By modifying the parameter from `address.plain()` to `publickKey`, I was able to correctly receive the metadata entered in the account.

`getAccountMetadataByKey()` and `getAccountMetadataByKeyAndSender()` have the same problem.

[https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/infrastructure/MetadataHttp.ts](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/infrastructure/MetadataHttp.ts)

This is the code that worked correctly.
```
/**
     * Returns the account metadata given an account id.
     * @param account - Account address to be created from PublicKey or RawAddress
     * @param queryParams - Optional query parameters
     * @returns Observable<Metadata[]>
     */
    getAccountMetadata(account, queryParams) {
        return rxjs_1.from(this.metadataRoutesApi.getAccountMetadata(account.publicKey, this.queryParams(queryParams).pageSize, this.queryParams(queryParams).id, this.queryParams(queryParams).order)).pipe(operators_1.map((response) => {
            const metadataEntriesDTO = response.body;
            return metadataEntriesDTO.metadataEntries.map((metadataEntry) => {
                return this.buildMetadata(metadataEntry);
            });
        }), operators_1.catchError((error) => rxjs_1.throwError(this.errorHandling(error))));
    }
```

**Comment by rg911** [comment]
This was the rest issue as not handling address properly. It seems this has been resolved in new rest pushes
