### ISSUE TITLE
Add Address.isValidAddress to check address validity with checksum

### ISSUE THREAD

**Issue by evias** [nemtech/nem2-sdk-typescript-javascript#324]
1. Expected behavior and actual behavior.

The method `Address.isValidAddress(address: string)` should be available as to verify the integrity/validity of an address using the checksum part.

2. Steps to reproduce the problem.

An example implementation can be found in catapult-rest: https://github.com/nemtech/catapult-rest/blob/master/catapult-sdk/src/model/address.js

3. Specifications like the version of the project, operating system, or hardware.

v0.14.3

**Comment by fboucquez** [comment]
Hi @evias @rg911 ,

Why is the catapult-rest's address always using sha3 and not keccak depending on the network type?

The Java and TS SDKs use a different hash algorithm depending on the network. For example:

https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/core/format/RawAddress.ts#L86

This is the Catapult SDK address class:

https://github.com/nemtech/catapult-rest/blob/master/catapult-sdk/src/model/address.js#L71

The hash algorithm for the address validation should depend on the network type to decide the algorithm.

**Comment by fboucquez** [comment]
Fixed in master
