### ISSUE TITLE
PersistentDelegationRequestTransaction static method should be create()

### ISSUE THREAD

**Issue by evias** [nemtech/nem2-sdk-typescript-javascript#344]
```
    public static createPersistentDelegationRequestTransaction(
        deadline: Deadline,
        delegatedPrivateKey: string,
        recipientPublicKey: string,
        senderPrivateKey: string,
        networkType: NetworkType,
        maxFee: UInt
```

replace with `create()` for consistency

**Comment by rg911** [comment]
Don't think it is possible as TS won't handle `override` as Java

**Comment by dgarcia360** [comment]
I think we could close this issue:

* ``create`` inherits from TransferTransaction, and allows you to create the ``PersistentDelegationRequestTransaction`` manually.
* ``createPersistentDelegationRequestTransaction`` abstracts the creation to be more developer friendly.
