### ISSUE TITLE
Instability of comparison UInt64 value.

### ISSUE THREAD

**Issue by 44uk** [nemtech/nem2-sdk-typescript-javascript#347]
1. Expected behavior and actual behavior.

I met unexpected behavior at comparing UInt64 values.
The problem has been occured from implicit string casting.

```js
const f = UInt64.fromHex('0000000000000006')
const g = UInt64.fromHex('0000000000000037')
console.log('f lt g => %o', d < e) // => "f lt g => false"
```

And when comparing [lower, higher] with number, It returns unexpected result.

```js
const b = UInt64.fromHex('FFFFFFFFFFFFFFFF')
const c = UInt64.fromHex('0000000000000001')
console.log('b gt c => %o', b.compact() > c.compact()) // "b gt c => false"
```

2. Steps to reproduce the problem.

https://runkit.com/embed/jebr6he9nn7n

3. Specifications like the version of the project, operating system, or hardware.

Browser and Node.js 

- nem2-sdk 0.14.4

Which way is the best comparison between UInt64 objects?

**Comment by rg911** [comment]
Note that compact might not give you the expected results as it won't handle if the value is  greater than 2^53.

Instead, you can cast Uint64 to  [Long](https://www.npmjs.com/package/long) and do the compare. 

e,g, 
```
const long_a = Long.fromBits(a.lower, a.higher, true);
const long_b = Long.fromBits(b.lower, b.higher, true);
return long_a.compare(long_b);
```

**Comment by 44uk** [comment]
Thanks you for this instruction.
I know Javascript supports maximum 53bit.
Do you plan to support comparing with Long type in UInt64 object?

**Comment by rg911** [comment]
Hi @44uk  yes, I am thinking adding a new method `Compare` to the Uint64 class which return `-1, 0, 1` as the Long package does.
