### ISSUE TITLE
Mosaic duration can't be extended

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#35]
**Expected behavior**

It is not possible to extend the mosaic duration using the SDK.

**Steps to reproduce the problem.**

1. Register a mosaic.

2. Extend the rental duration for 10 blocks. Announce a ``MosaicDefinitionTransaction`` setting the properties used in the previous step.

```
MosaicDefinitionTransaction.create(
    Deadline.create(),
    mosaicName,
    namespaceName,
    MosaicProperties.create({
        supplyMutable: true,
        transferable: true,
        levyMutable: true,
        divisibility: 0,
        duration: UInt64.fromUint(10)
    }),
    NetworkType.MIJIN_TEST);
```

3. Receive the message ``Failure_Mosaic_Modification_Disallowed``  through the status WebSocket.

**Specifications like the version of the project, operating system, or hardware.**

* nem2-sdk 0.10.1
* Windows 10

**Comment by dgarcia360** [comment]
Closing this issue as #36 treats the same problem.

**Comment by rg911** [comment]
I cannot reproduce this one, has it been fixed already?
