### ISSUE TITLE
MaxFee improvement

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#353]
1. Expected behavior and actual behavior.

By definition, the effective fee is calculated as ``effectiveFee=transaction::size∗block::feeMultiplier``. 

For that reason, we need to know the transaction's size before announcing it to the network and multiply it by an estimated maximum value to get an estimated maximum value we are willing to pay.

Although it's possible to retrieve the transaction's size, this is only possible once the fee has been defined. This leads to having to create the ``Transaction`` object twice: the first time to get the ``Transaction`` object size, and the second one to add the correspondent ``maxFee`` value.

Let's discuss in this issue how we can solve this problem. Ideally, it should be possible to define an arbitrary ``maxFee``, but just to pass a multiplier to not to have to know the transaction' size beforehand.

2. Steps to reproduce the problem.

To set a reasonable ``maxFee``, we need to define the same tx twice:

````
const size = SecretProofTransaction.create(
    Deadline.create(),
    HashType.Op_Sha3_256,
    secret,
    bobPrivateChainAccount.address,
    proof,
    NetworkType.MIJIN).size;

const maxFee = UInt64.fromUint(size * 2);

const transaction = const size = SecretProofTransaction.create(
    Deadline.create(),
    HashType.Op_Sha3_256,
    secret,
    bobPrivateChainAccount.address,
    proof,
    NetworkType.MIJIN,
    maxFee);
````

**Comment by fboucquez** [comment]
Good catch David.  In java we have the factories. We can calculate the fee
before the transaction is created and the user can update the max fee
before getting the final transaction. I'll work on examples.

**Comment by fboucquez** [comment]
Good catch David.  In java we have the factories. We can calculate the fee
before the transaction is created and the user can update the max fee
before getting the final transaction. 

Example:

```
TransferTransactionFactory factory = TransferTransactionFactory.create(
       getNetworkType(),
       recipient.getAddress(),
       Collections.singletonList(NetworkCurrencyMosaic.createAbsolute(amount)),
       new PlainMessage("Some Message")
);
factory.maxFee(BigInteger.valueOf(2 * factory.getSize()));
TransferTransaction transferTransaction = factory.build();
```

**Comment by evias** [comment]
This problem is general to any fields in transactions.

I have elevated the issue with for example `addTransactions` and `addCosignatures` in AggregateTransaction.

Talking about `maxFee` is the same, making it editable outside the constructor fixes the problem.

Factories seem to be good but add one more layer of classes to maintain and unsure whether there should be a factory for each type of transaction or one factory (à la `CreateTransactionFromDTO` monster).

**Comment by fboucquez** [comment]
Hi @dgarcia360 , should we get the maxFee multiplier (2 in your example) from rest/server? What's the best way to load it?

**Comment by rg911** [comment]
FeeMultiplier is currently returned in `BlockInfo`. So IMO Option would be
1. Make the `maxFee` mutable by removing the `readonly` / adding a setter etc... and feeMultiplier can be getter from `BlockInfo` by calling the rest endpoint. 
2. Auto calculate maxFee when announcing (MergeMap the BlockInfo), then add the actually maxFee in the response payload to inform the announcer?

**Comment by dgarcia360** [comment]
⚠️ Note that there is not a single valid ``feeMultiplier`` value. The account defining the transaction could decide to pay more or fewer fees to get their transaction accepted faster.

What we are proposing here is to have an endpoint to receive a range of recommended  ``feeMultipliers`` based on the latest network behavior (last maxRollBackBlocks): https://github.com/nemtech/catapult-rest/issues/98

> averageFeeMultiplier = average fee multiplier over a period of maxRollbackBlocks.
> medianFeeMultiplier = median fee multiplier over a period of maxRollbackBlocks.
>highestFeeMultiplier = highest fee multiplier over a period of maxRollbackBlocks.
> lowestFeeMultiplier = lowest fee multiplier over a period of maxRollbackBlocks.

**Comment by dgarcia360** [comment]
I believe that this issue does not have any dependency to be blocked. Without the REST endpoint, we can still define max_fee based on the transaction size:

```
 SecretProofTransaction.createWithFeeMultiplier(
    Deadline.create(),
    HashType.Op_Sha3_256,
    secret,
    bobPrivateChainAccount.address,
    proof,
    NetworkType.MIJIN,
    2 ) // size * 2 (multiplier)
```
or as @fboucquez has defined before using a factory:

```
TransferTransactionFactory factory = TransferTransactionFactory.create(
       getNetworkType(),
       recipient.getAddress(),
       Collections.singletonList(NetworkCurrencyMosaic.createAbsolute(amount)),
       new PlainMessage("Some Message")
);
factory.maxFee(BigInteger.valueOf(2 * factory.getSize()));
TransferTransaction transferTransaction = factory.build();
```

What https://github.com/nemtech/catapult-rest/issues/98 will provide is the optimal network multiplier (2 in the examples above), but to get this value we can create an issue once the endpoint is implemented.
