### ISSUE TITLE
signWith not exposed

### ISSUE THREAD

**Issue by decentraliser** [nemtech/nem2-sdk-typescript-javascript#364]
https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/579f589cc98fede718cdf69bcbc550d7046b8722/src/model/transaction/Transaction.ts#L120

Is there any particular reason why `signWith` is kept internal?
It would be handy to have it available for unit testing

**Comment by dgarcia360** [comment]
You can call the function from the account model: https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/579f589cc98fede718cdf69bcbc550d7046b8722/src/model/account/Account.ts#L156

**Comment by rg911** [comment]
yeah you can use `Account.sign`. can't see it causes issues here as you ll need the account with sign.with anyway?

**Comment by decentraliser** [comment]
Rig
