### ISSUE TITLE
[Fushicho 3] Added epochAdjustment network configuration field

### ISSUE THREAD

**Issue by evias** [nemtech/nem2-sdk-typescript-javascript#370]
The `epochAdjustment` field affects `Deadline` creation. This field should ultimately be retrieved from REST but currently is set inside the `Deadline` class and needs a change with Fushicho 3 (catapult-server@v0.9.1.1).

**Comment by fboucquez** [comment]
@evias @Vektrat , do you have plans to add the configuration in rest? Would it be prioritized next week?

**Comment by rg911** [comment]
setFee by feeMultiplier has been added. Wait for catapult-rest's endpoint implementation

**Comment by evias** [comment]
> do you have plans to add the configuration in rest? Would it be prioritized next week?

I do not think it should be prioritized in SDK for now ; The fact that this  "somewhat magic number" is static in the SDK helps reduce the number of requests done before I can announce a transaction (I would need it before signature actually..).

Overall, the solution is ugly but does the job perfectly. I would suggest that *in the same principle* as done with networkType, the epochAdjustment would be a configuration field that can be *overwritten* through the SDK in the case that the user wants to use a "already known" epochAdjustment and thereby avoid an extra network request
