### ISSUE TITLE
unit tests still/again not running on travis

### ISSUE THREAD

**Issue by evias** [nemtech/nem2-sdk-typescript-javascript#372]
There was a fix for this a few months back, something must be wrong with the travis configuration

@dgarcia360 @rg911 https://travis-ci.org/nemtech/nem2-sdk-typescript-javascript/jobs/622141554?utm_medium=notification&utm_source=github_status

anyways, tests don't run anymore.

For instance ; currently `master` breaks as can be seen in latest commit here on github ; while travis tells you its fine because it breaks at `coveralls`.

I believe with current state of the SDK it would make sense to disable coveralls until fixed and thereby have unit tests running again :+1:

**Comment by fboucquez** [comment]
Unit tests are working again

https://travis-ci.org/nemtech/nem2-sdk-typescript-javascript/jobs/622705570

Do you see any nemtech repo in coveralls? @evias @rg911 

https://coveralls.io/repos

**Comment by evias** [comment]
thanks guys.
