### ISSUE TITLE
Operations with UInt64

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#376]
**1. Expected behavior and actual behavior.**

``UInt64`` class does not allow operating with the value. To start, we could support **add()** and **subtract()** capabilities.

**2. Steps to reproduce the problem (example)**

Catapult transactions can be rolled back up to a certain amount of blocks. We say that every time there is a new block, the transaction receives a confirmation. The more confirmation transaction has, the fewer chances this is rolled-back.

To determine if we can consider a transaction as persistent, we need to compare the current blockchain height with the transaction blockchain height. Then, determine if the difference is higher than a certain number we consider good enough to consider the transactions as confirmed. This can be calculated as:

````
isTransactionPersistent = (currentBlockchainHeight - transactionHeight >= (confirmationsToConsiderTransacitionPersistent);`
 ````

Note that right now, it is only possible to do ``(currentBlockchainHeight - transactionHeight)`` if the height is small enough and does not overflow when calling ``height.compact()``.

**Comment by fboucquez** [comment]
Java moved from custom int array for +unit64 to a more native BigInteger several months ago. All the operations and documentation are out of the box.

Should ts move to a more standard big int implementation? What's the best library out there?

**Comment by dgarcia360** [comment]
@fboucquez As far as I know, there is no native long type in TypeScript. I assume that the original SDK devs created the UInt64 class following the adapter pattern to not depend too much on an external library and be able to replace it if necessary.

We are currently using ``long`` library https://www.npmjs.com/package/long underneath.

**Comment by fboucquez** [comment]
@dgarcia360 thanks!, Who is we? Which project? would be long good/small enough for ts sdk?

**Comment by dgarcia360** [comment]
We --> the nem2-sdk-typescript-javascript project (https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/package.json#L65)

**Comment by fboucquez** [comment]
Ok, so why not just replacing UInt64 with Long? Is it only for the abstraction?

**Comment by fboucquez** [comment]
https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/model/transaction/TransferTransaction.ts#L186 using Long directly breaking the abstraction if you want to keep it.
