### ISSUE TITLE
To inject http repositories into all services and integrations. 

### ISSUE THREAD

**Issue by rg911** [nemtech/nem2-sdk-typescript-javascript#381]
At the moment, the services and integrations were using the concrete class rather than interface.  It should be changed to use interface instead

**Comment by fboucquez** [comment]
An example of the change
https://github.com/nemtech/nem2-sdk-typescript-javascript/pull/380/commits/3f950ba44d6f21b9d8d70a4f201f82d913896388#diff-7c3513151c4050e9fcc3c044925b201bL44
