### ISSUE TITLE
An account that has never sent a transaction cannot obtain information using accountHttp.getAccountTransactions ().

### ISSUE THREAD

**Issue by m1z0-753** [nemtech/nem2-sdk-typescript-javascript#382]
An account that has never sent a transaction (for example, an account that has just received a coin) cannot obtain information using `accountHttp.getAccountTransactions ()`.

This is because it is obtained using only the address.
If it can be obtained with publicKey, it will be solved.
(It can be obtained by using RESTAPI directly using publicKey)

I can't get these on accountHttp as well.
```
getAccountTransactions ()
getAccountIncomingTransactions ()
getAccountOutgoingTransactions ()
getAccountUnconfirmedTransactions ()
etc ...
```

I hope that these can be obtained using publicKey even when using SDK.

**Comment by rg911** [comment]
This sounds to me an issue on the server side, as currently catapult-rest takes either Address or PublicKey for those endpoints. The reason we use Address here is because SDK user can choose to use address (string) or publicKey either way. E.g. `Address.createFromRaw(address)` or `PublicAccount.createFromPubKey(pubKey).address`;

@Vektrat @dgarcia360

**Comment by m1z0-753** [comment]
> This sounds to me an issue on the server side, as currently catapult-rest takes either Address or PublicKey for those endpoints.
That is true. Thank you for your reply.

**Comment by dgarcia360** [comment]
Hi @m1z0-753, thanks for the report. I believe that this has been fixed recently in this PR: https://github.com/nemtech/catapult-rest/pull/218

Just to confirm, could you share with us the version of the catapult-rest your node is using? You can find it by opening in a new tab ``http://<nodeHost>:3000/diagnostic/server

**Comment by m1z0-753** [comment]
> Just to confirm, could you share with us the version of the catapult-rest your node is using? 

```
"serverInfo": {
"restVersion": "1.0.20.1",
"sdkVersion": "0.7.20.1"
}
```

I wait for the next version. Thank you.
