### ISSUE TITLE
TransactionHttp#getTransactionStatus doesn't return an error reason.

### ISSUE THREAD

**Issue by 44uk** [nemtech/nem2-sdk-typescript-javascript#387]
1. Expected behavior and actual behavior.

Result of TransactionHttp#getTransactionStatus doesn't contain an error reason.
I think there is no way to get an error reason using SDK.

2. Steps to reproduce the problem.

```javascript
import { TransactionHttp } from "nem2-sdk"

const txHttp = new TransactionHttp("http://api-01.us-east-1.nemtech.network:3000")
txHttp.getTransactionStatus("8F4654BC708421BFBB3C7C4EDB5BD6AF16E376B0A3E58182E4FF2B6075F2373B")
  .subscribe(
    status => console.debug(status)
  )

/*
TransactionStatus {
  status: undefined,
  group: 'failed',
  hash: '8F4654BC708421BFBB3C7C4EDB5BD6AF16E376B0A3E58182E4FF2B6075F2373B',
  deadline: Deadline { value: LocalDateTime { _date: [LocalDate], _time: [LocalTime] } },
  height: undefined
}
*/
```

Get from API Endpoint:

http://api-01.us-east-1.nemtech.network:3000/transaction/8F4654BC708421BFBB3C7C4EDB5BD6AF16E376B0A3E58182E4FF2B6075F2373B/status

```javascript
{
  hash: "8F4654BC708421BFBB3C7C4EDB5BD6AF16E376B0A3E58182E4FF2B6075F2373B",
  code: -2143092733,
  deadline: "116822518510",
  group: "failed"
}
```

`code: -2143092733` means `Failure_Core_Insufficient_Balance`

Hash "8F4654BC708421BFBB3C7C4EDB5BD6AF16E376B0A3E58182E4FF2B6075F2373B" might be removed when you see because of the transaction had not been confirmed.

3. Specifications like the version of the project, operating system, or hardware.

Node: http://api-01.us-east-1.nemtech.network:3000
serverInfo:
  restVersion: 1.0.20.2
  sdkVersion: 0.7.20.2

SDK: v0.15.1

**Comment by evias** [comment]
the SDK is missing the `code` field in the status response @rg911

**Comment by rg911** [comment]
shouldn't the rest returns the interpreted status rather than code?

**Comment by Vektrat** [comment]
the mongodb collection was most likely changed, we will update REST after confirmation

**Comment by fboucquez** [comment]
Latest bootstrap is returning the status text

![image](https://user-images.githubusercontent.com/5390558/70797735-d635e900-1d83-11ea-9015-050409e25ed3.png)

If rest is changed, @dgarcia360 open API and the java SDK would also need to change.
