### ISSUE TITLE
check if an aggregate complete transaction has all cosignatories

### ISSUE THREAD

**Issue by gimyboya** [nemtech/nem2-sdk-typescript-javascript#4]
From this [doc issue](https://github.com/nemtech/nem2-docs/issues/10) we need a method that given an Aggregate complete transaction needs to check if this transaction has all cosignatories required and ready to be announced

> An Aggregate Complete Transaction has to know if he has all the required cosignatures, up to date, it's developer responsibility to know and check the cosignatures in a manual way. We should create a method in the `nem2-sdk` that given an ACT, check if it has all the required cosigners automatically.

```typescript
isComplete(signedAggregateCmpleteTransaction: SignedTransaction): boolean;
```
**Summary of requirements**

- Create an easier way to re-create the ACT.
- Serialization
- Check ACT status with chain information

**Comment by aleixmorgadas** [comment]
Because it requires network results, we will need to create a service that leads to all network calls.

**Comment by rg911** [comment]
this is depend on PR https://github.com/nemtech/nem2-sdk-typescript-javascript/pull/86 to be merged first

**Comment by dgarcia360** [comment]
Here you have an initial specification you can use (@rg911, @evias) for reviewing the PR:

>   Scenario: An escrow contract is signed by all the participants (normal accounts)
    Given Alice defined the following escrow contract:
      | sender | recipient | type             | data                    |
      | Alice    | Bob       | send-an-asset | 1 concert.ticket |
      | Bob      | Alice     | send-an-asset | 20 euros            |
    And Bob signs the contract
    And Alice signs the contract
    Then the contract should appear as complete

>   Scenario: An account contract signed by some participants (normal accounts)
    Given Alice defined the following escrow contract:
      | sender | recipient | type             | data                    |
      | Alice    | Bob       | send-an-asset | 1 concert.ticket |
      | Bob      | Alice     | send-an-asset | 20 euros            |
    And Alice signs the contract
    Then the contract should appear as incomplete


>   Scenario: An account contract signed by some participants (multisig accounts)
    Given Bob is a 2-of-2 multisig contract with cosignatories:
     | cosignatory |
     | Phone          |
     | Computer    |
    Given Alice defined the following escrow contract:
      | sender | recipient | type             | data                    |
      | Alice    | Bob       | send-an-asset | 1 concert.ticket |
      | Bob      | Alice     | send-an-asset | 20 euros            |
    And Alice signs the contract
    Then the contract should appear as incomplete


Gi*Inner transactions: AliceTransferTransactionToBob, BobTransferTransactionToAlice
* Sender: Alice

If complete? No, Bob is missing
If Signers: Bob is complete? Yes!

*2) Multisig account*
- Alice: normal account
- Bob: 2-of-2 multisig account, with cosignatories Phone (normal account) and Computer (normal account)

ACT:
- Inner transactions: AliceTransferTransactionToBob, BobTransferTransactionToAlice
- Sender: Alice

isComplete()? No, Bob signature is missing
If Signers: Computer is complete? No, Bob is a 2-of-2 multisig.
If Signers: Computer, Phone is complete? Yes!

*3) MLMA*
- Alice: normal account
- Bob: 2-of-2 multisig account, with cosignatories Phone (normal account) and Computer (multisig account).
- Computer: 2-of-2 multisig account with cosignatories browser (normal account) and App(normal account)

ACT:
- Inner transactions: AliceTransferTransactionToBob, BobTransferTransactionToAlice
- Sender: Alice

isComplete()? No, Bob signature is missing
If Signers: Phone is complete? No, Bob is a 2-of-2 multisig.
If Signers: Phone, Browser is complete? No, Computer is a 2-of-2 multisig.
If Signers: Phone, Browser, App is complete? Yes!

**Comment by dgarcia360** [comment]
@rg911 Here you have a specification to test this issue before merging:

* Success: https://github.com/nemtech/nem2-scenarios/blob/master/features/escrow/create_an_escrow_contract.feature#L33-L76
* Failure: https://github.com/nemtech/nem2-scenarios/blob/master/features/escrow/create_an_escrow_contract.feature#L176-L216
