### ISSUE TITLE
SDK WebSocket listener.status is not throwing errors after 0.16.0 release

### ISSUE THREAD

**Issue by ugniusvers** [nemtech/nem2-sdk-typescript-javascript#411]
After announcing a transaction a listener.status is expected to throw an error if there is any. This was happening in previous versions of nem2-sdk. In 0.16.0 and 0.16.1 versions - nothing is updated or shown in this WebScoket.

Using:
nem2-sdk-typescript-javascript - v0.16.1
catapult-server - v0.9.1.1: Fushicho 3 (RC2)

 // Listen to status
            listener.status(accountAddress)
                .pipe(filter(error => error.hash === transaction.hash))
                .subscribe(error => {
                   console.log(error.status);
                    listener.close();
                }, error => {
                    console.log(error.message);
                });

**Comment by rg911** [comment]
Schema change in catapult-rest: `status` -> `code`
