### ISSUE TITLE
Error in node_modules - nem2-sdk-openapi-typescript-node-client

### ISSUE THREAD

**Issue by ugniusvers** [nemtech/nem2-sdk-typescript-javascript#418]
error TS2694: Namespace '"http"' has no exported member 'ClientResponse'
response: http.ClientResponse;

54 errors in different files

node_modules/nem2-sdk-openapi-typescript-node-client/dist/api/accountRoutesApi.d.ts:27:24
node_modules/nem2-sdk-openapi-typescript-node-client/dist/api/blockRoutesApi.d.ts:26:24 
node_modules/nem2-sdk-openapi-typescript-node-client/dist/api/chainRoutesApi.d.ts:33:24 
...

Using 
Client Library | v0.7.20-alpha.6
Catbuffer Library v0.0.7
"nem2-sdk": "^0.16.2",

"@types/node": "^13.1.4",
"ts-node": "^8.5.4",
"tslint": "^5.20.1",
"tslint-config-prettier": "^1.18.0",
"typescript": "^3.7.4"

**Comment by rg911** [comment]
seems working fine for me . can you post more details of how you called the endpoint pls?

**Comment by rg911** [comment]
It seems a bug here if the `@types/node` version in client up is greater than 8 as 'http. ClientResponse` is deprecated and not supported in ES6.
