### ISSUE TITLE
(Bug) Listener.unconfirmed() and confirmed() are returning multiple result of 1 aggregate transaction.

### ISSUE THREAD

**Issue by aizaiz** [nemtech/nem2-sdk-typescript-javascript#42]
Aggregate Transaction = ATx.

1. Expected behavior and actual behavior.
Expected behaviour: Only listening once for every ATx.
Actual behaviour: for the first ATx the listener is returning only 1 transaction, but the next transaction it returns multiple transactions of the same ATx.

2. Steps to reproduce the problem.
    a. create 3 multisig account and then create 1  account A as a cosignatory of those 3 accounts
    b. create a listener of Account A.
    c. create account B
    d. make account A to change the cosignatory of 1 multisig account from Account A to Account B
    e. check the listener if Account A.
    f. repeat step d & e 2 more times.

**Comment by rg911** [comment]
Is tha a SDK issue or rest issue?
