### ISSUE TITLE
Improve types in methods

### ISSUE THREAD

**Issue by fboucquez** [nemtech/nem2-sdk-typescript-javascript#432]
Currently, there are some methods without types in either parameters or returned values.

Most of them are in the crypto folder

Examples:

- https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/core/crypto/Utilities.ts
- https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/core/crypto/KeyPair.ts#L27 (KeyPar interface or class?)
- https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/core/crypto/SHA3Hasher.ts#L30

This issue is to add types to those methods so the method contract is clear.

**Comment by rg911** [comment]
already merged
