### ISSUE TITLE
Deadline unit test fails if run after 22h.

### ISSUE THREAD

**Issue by rg911** [nemtech/nem2-sdk-typescript-javascript#44]
1. Expected behavior and actual behavior.

Deadline.spec.ts: 'should createComplete timestamp today', if run after 22h of the day it will fail. Default constructor parameter adds 2 hours to current datetime which makes the deadline 'Day' === day + 1. Potentially could break CI build.

2. Steps to reproduce the problem.

npm run test after 22h of the day.

3. Specifications like the version of the project, operating system, or hardware.

**Comment by evias** [comment]
fixed with PR nemtech/nem2-sdk-typescript-javascript#71
