### ISSUE TITLE
Rejected transactions with invalid type

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#45]
HashLockTransaction entity code has changed and this has not been reflected in the SDK.

After sending a HashLockTransaction, catapult returns the following error:

> api-node-0_1              | 2019-02-07 13:45:06.497553 0x00007f1ebd869700: <warning> (model::Transaction.cpp@31) rejected transaction with type: EntityType(0x414C)
> api-node-0_1              | 2019-02-07 13:45:06.498598 0x00007f1ebd869700: <warning> (ionet::PacketPayloadParser.h@34) entity (header size = 120) has failed validity check with size 176
> api-node-0_1              | 2019-02-07 13:45:06.499150 0x00007f1ebd869700: <warning> (handlers::HandlerUtils.h@39) rejecting empty range: packet Push_Transactions with size 184

HashLockTransaction entity code, among others, has changed and this has not been reflected in the SDK.

Review all of them: https://github.com/nemtech/catapult-rest/commit/d81a7417d5c5d6f4b129c555e856144ef8c849ba ( [File](https://github.com/nemtech/catapult-rest/blob/master/catapult-sdk/src/model/EntityType.js))

**Comment by Vektrat** [comment]
review all of them: https://github.com/nemtech/catapult-rest/commit/d81a7417d5c5d6f4b129c555e856144ef8c849ba

**Comment by evias** [comment]
I modified the **changed types** which were *hashLock*, *secretLock* and *secretProof* but also included some of the others to hold their uppercase representation, this is just to keep consistent on how we handle hexadecimal notation.
