### ISSUE TITLE
QueryParams - Allow passing arguments to the constructor

### ISSUE THREAD

**Issue by decentraliser** [nemtech/nem2-sdk-typescript-javascript#456]
https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/42fb1dd38bcfe7978b10059056f263753b836b93/src/infrastructure/QueryParams.ts#L51

Could we allow passing the pageSize and order as constructor arguments?

**Comment by dgarcia360** [comment]
+1, I experienced the same issue when migrating to 0.17.

**Comment by decentraliser** [comment]
PR incoming

**Comment by fboucquez** [comment]
The way you can set up params in 0.17 is builder style:

````
const params = new QueryParams().setId("someId").setOrder(Order.ASC).setPageSize(25);
````

**Comment by decentraliser** [comment]
pushed a proposition

It's a bit verbose not to be able to pass args to the constructor

**Comment by fboucquez** [comment]
I like your proposal for destructuring params in typescript. It's great that you can keep the types in the passed object.
