### ISSUE TITLE
Adapt serialization using the new buffers

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#47]
From [Medium](https://medium.com/nem-europe/nem-catapult-a-new-server-release-cow-95ec47cb82cc), transactions that are sent to the NEM2 REST gateway are serialized earlier in the SDK. Until now, the serialization was done by the flatbuffer library (Google). This library will be replaced by a custom library called catbuffer.

### 1. Generating the buffer classes

Install the catbuffer tool and compile the schema for javascript [https://github.com/nemtech/catbuffer#parse-an-schema-and-generate-transaction-builders](https://github.com/nemtech/catbuffer#parse-an-schema-and-generate-transaction-builders)

Move the generated files to your model/transaction SDK folder.

### 2. Adapt the Schema class

This [class](https://github.com/nemtech/nem2-library-js/blob/f171afb516a282f698081aea407339cfcd21cd63/src/schema/Schema.js) is used to generate SDK schemas.

### 3. Adapt the transaction schemas

This [folder](https://github.com/nemtech/nem2-library-js/tree/master/src/schema) contains the transaction schemas.

### 4. Using the schemas in the Transaction Models

Each Transaction has to implement [build](https://github.com/nemtech/nem2-library-js/blob/master/src/transactions/AggregateTransaction.js#L67) method using the buffers and the schemas.

ℹ️  This text was adapted from https://nemtech.github.io/sdk/development.html, where flatbuffers where used. Evaluate if this process has to be changed when working with catbuffers for the first time.

**Comment by Vektrat** [comment]
note: catbuffers is in early stages, it is possible that they need to be reviewed/updated and adapted to potential needs that appear - don't overpanic, they should be fine, but they still need to be put into practice for the first time and require some tuning, it's just a word of caution to avoid blind faith ^^
