### ISSUE TITLE
Mosaic / Namespace split

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#48]
[Mosaics Changelog](https://github.com/nemtech/catapult-server/blob/master/CHANGELOG.md#changed)

### Register a mosaic

``` MosaicDefinitionTransaction.create(
    Deadline.create(),
    MosaicProperties.create({
        supplyMutable: true,
        transferable: true,
        levyMutable: false,
        divisibility: 0,
        duration: UInt64.fromUint(0) //nonExpirable
    }),
    NetworkType.MIJIN_TEST);
```

Remove ``mosaicName`` and ``namespaceId``. Ideally, the nonce should not be set by the user, as it is a random number. However, it can be defined as an optional parameter in case some advanced user wants to define its own.

A mosaic can be set non-expirable when it's duration is set to 0. Should we provide a way to set that the mosaic is non-expirable clearly? E.g. : ``MosaicDefinitionTransaction.createNonExpirable()``

### Remove "get mosaic by namespace from the mosaic" from MosaicRepository

[Method](https://nemtech.github.io/nem2-sdk-typescript-javascript/interfaces/_infrastructure_mosaicrepository_.mosaicrepository.html#getmosaicsfromnamespac) here.

### Adapt models related to mosaics

* The [constructor ](https://nemtech.github.io/nem2-sdk-typescript-javascript/classes/_model_mosaic_mosaicid_.mosaicid.html
) of ``MosaicId`` class accepts a string in ``namespace_name:mosaic_name`` form.

* Mosaics don't have a name by default, now have an alias. Consider editing / deleting [MosaicNames](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/4227619494ae216940295db96e89e2af53468312/src/model/mosaic/MosaicName.ts) model

* [XEM ](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/4227619494ae216940295db96e89e2af53468312/src/model/mosaic/XEM.ts)definition has changed since it does not have the namespace "nem" attached. 

* Consider how to deal with "fullName" field, now we have the alias: https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/4227619494ae216940295db96e89e2af53468312/src/model/mosaic/MosaicId.ts

### Adapt services related to mosaics

The following related mosaic services use the namespaceId, namespaceName or namespaceHttp:

* [MosaicAmountView](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/4227619494ae216940295db96e89e2af53468312/src/service/MosaicAmountView.ts)
* [MosaicView](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/4227619494ae216940295db96e89e2af53468312/src/service/MosaicView.ts)
* [MosaicService](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/4227619494ae216940295db96e89e2af53468312/src/service/MosaicService.ts)

**Comment by dgarcia360** [comment]
@Vektrat Added some comments after reviewing the code (Adapt models and services related to mosaics)
*

**Comment by Vektrat** [comment]
https://github.com/nemtech/nem2-sdk-typescript-javascript/issues/60 to add custom nonce

with regard to aliases, i'd keep this as a different set of tasks as well, this task's goal is to get mosaics working ASAP - will see how we deal with some things like the XEM alias, same goes for the fullname alias, this sounds tricky without aliases implemented

**Comment by Vektrat** [comment]
dropped work on this issue, transferred to greg

**Comment by dgarcia360** [comment]
@Vektrat Agree, alias is referenced in #55. This issue only treats mosaic changes.
