### ISSUE TITLE
Update BlockInfo attributes

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#49]
Add the following attributes to the [BlockInfo](https://nemtech.github.io/nem2-sdk-typescript-javascript/classes/_model_blockchain_blockinfo_.blockinfo.html).

<table>
  <tr>
   <td>feeMultiplier
   </td>
   <td>uint32
   </td>
   <td>The fee multiplier applied to transactions contained in block.
   </td>
  </tr>
  <tr>
   <td>previousBlockHash
   </td>
   <td>32 bytes (binary)
   </td>
   <td>The hash of the previous block.
   </td>
  </tr>
  <tr>
   <td>blockTransactionHash
   </td>
   <td>32 bytes (binary)
   </td>
   <td>The transactions included in a block are hashed forming a <a href="https://en.wikipedia.org/wiki/Merkle_tree">merkle tree</a>. The root of the tree summarizes them.
   </td>
  </tr>
  <tr>
   <td>blockReceiptsHash
   </td>
   <td>32 bytes (binary)
   </td>
   <td>The collection of <a href="https://nemtech.github.io/concepts/receipt.html">receipts</a> are hashed into a <a href="https://en.wikipedia.org/wiki/Merkle_tree">merkle tree</a> and linked to a <a href="https://nemtech.github.io/concepts/block.html#">block</a>. The block header stores the root hash.
   </td>
  </tr>
  <tr>
   <td>stateHash
   </td>
   <td>32 bytes (binary)
   </td>
   <td>The state of the blockchain is stored in RocksDB for each block, forming a <a href="https://en.wikipedia.org/wiki/Radix_tree">patricia tree</a>. The root of the tree summarizes the state of the blockchain for a given block.
   </td>
  </tr>
  <tr>
   <td>beneficiaryPublicKey
   </td>
   <td>32 bytes (binary)
   </td>
   <td>The public key of the optional beneficiary designated by harvester.
   </td>
  </tr>
</table>

**Comment by evias** [comment]
Currently available fields are:

| field | type |
| hash | string |
| generationHash | string |
| totalFee | UInt64 |
| numTransactions | number |
| signature | string |
| signer | PublicAccount |
| networkType | NetworkType |
| version | number |
| type | number |
| height | UInt64 |
| timestamp | UInt64 |
| difficulty | UInt64 |
| previousBlockHash | string |
| blockTransactionsHash | string |

I will be adding the fields you listed - just making sure, in your table you mention **blockTransactionHash** (without an `s` at Transaction), is this the same field as the one I listed in my table (last field).

**Comment by dgarcia360** [comment]
@evias you are right - the correct one is ``blockTransactionsHash``.

**Comment by evias** [comment]
The SDK needs a lot more documentation in the source code. Uses must currently check the SDK source code to be able to tell *ordering of parameters*. And with such big parameters list it can get very frustrating.

I am bringing this up here, because the [BlockInfo class](https://github.com/evias/nem2-sdk-typescript-javascript/blob/e636ff3d26a9bdf5c1eb82dddc2007471a522ae4/src/model/blockchain/BlockInfo.ts) is one of those with many parameters and I wish to know if **there is a preferred ordering of parameters for this change ?**

**Comment by dgarcia360** [comment]
@evias I'd opt to follow the order specified in catapult-server https://github.com/nemtech/catapult-server/blob/8467be1485db44d60a9704ddf2eeab9050273911/src/catapult/model/Block.h#L34
