### ISSUE TITLE
Account Properties

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#50]
Account Filter docs: https://nemtech.github.io/concepts/account-filter.html

### Set account filters

```
const addressFilterExample = Filter.createForAddress(
    PropertyModificationType.Add, // Options: Add, Remove
    address
);

const mosaicFilterExample = Filter.createForMosaic(
    PropertyModificationType.Add, 
    mosaicId
);

const mosaicFilterExample = Filter.createForEntityType(
    PropertyModificationType.Add, 
    TransactionType.TRANSFER
);

AccountPropertiesTransaction.create(
    Deadline.create(),
    PropertyType.BlockAddress, // Allow(Block)Address, Allow(Block)Mosaic, Allow(Block)EntityType
    [addressFilterExample],
    NetworkType.MIJIN_TEST);
```

### Get account properties from an account

```
accountHttp.getProperties(publicAccount: PublicAccount, queryParams: QueryParams): Observable<AccountProperties[]>

```

**Comment by rg911** [comment]
this one with me

**Comment by rg911** [comment]
Regards the input from @BloodyRookie, entity type transaction requires itself to be allowed first in order to be able to grant other types. We probably need checks either on SDK or the server. Open for discussion.  @dgarcia360 @evias

**Comment by evias** [comment]
Implementation of AccountProperties added with [v0.10.3-4](https://github.com/nemtech/nem2-sdk-typescript-javascript/releases/tag/v0.10.3-4)

Pending features: `class Filter` @rg911

**Comment by dgarcia360** [comment]
I'

**Comment by dgarcia360** [comment]
I reopen this to comment some developer experience issues I found while testing the feature.

1) ``AccountPropertyTransaction.createAddressFilter`` should be created with a different class (e.g. "FilterModification" or just "Filter"). The reason behind is to follow the same approach already implemented in [MultisigCosignatoryModification](https://nemtech.github.io/guides/account/modifying-a-multisig-account.html#adding-a-new-cosignatory) when sending a multisig transaction.

**Current approach**
```
const filter = AccountPropertyTransaction
    .createAddressFilter(
        PropertyModificationType.Add,
        Address.createFromRawAddress('SC5DT5Y4DZ7ATYFSWSUX76FAWL6O4ZS2UZ5QSCWF')
    );
```
**Proposed approach**

```
const filter = new FilterModification(
    PropertyModificationType.Add, 
    Address.createFromRawAddress('SC5DT5Y4DZ7ATYFSWSUX76FAWL6O4ZS2UZ5QSCWF')
);
```

2) A transaction can be created with  ``AccountPropertyTransaction.createAddressPropertyModificationTransaction``. Then, it's possible to pass an incorrect property type, such as "PropertyType.AllowMosaic". 

The SDK could detect the property type and create the transaction accordingly to be less error prone.

**Current approach**

```
const transaction = AccountPropertyTransaction.createAddressPropertyModificationTransaction(
    Deadline.create(),
    PropertyType.AllowAddress,
    [filter],
    NetworkType.MIJIN_TEST
);
```

**Proposed approach**

```
AccountPropertiesTransaction.create(
    Deadline.create(),
    PropertyType.BlockAddress,
    [filter],
    NetworkType.MIJIN_TEST);
```

**Comment by dgarcia360** [comment]
I reopen this to comment a developer experience issue I found while testing the feature.

``AccountPropertyTransaction.createAddressFilter`` should be created with a different class (e.g. "FilterModification" or just "Filter"). The reason behind is to follow the same approach already implemented in [MultisigCosignatoryModification](https://nemtech.github.io/guides/account/modifying-a-multisig-account.html#adding-a-new-cosignatory) when sending a multisig transaction.

**Current approach**
```
const filter = AccountPropertyTransaction
    .createAddressFilter(
        PropertyModificationType.Add,
        Address.createFromRawAddress('SC5DT5Y4DZ7ATYFSWSUX76FAWL6O4ZS2UZ5QSCWF')
    );
```
**Proposed approach**

```
const filter = new FilterModification(
    PropertyModificationType.Add, 
    Address.createFromRawAddress('SC5DT5Y4DZ7ATYFSWSUX76FAWL6O4ZS2UZ5QSCWF')
);
```

**Comment by dgarcia360** [comment]
``createEntityTypeFilter(modificationType: PropertyModificationType, entityType: number)`` accepts a number as an entityType parameter.

It should be more usable if the [TransactionType ](https://nemtech.github.io/nem2-sdk-typescript-javascript/classes/_model_transaction_transactiontype_.transactiontype.html) is used instead.
