### ISSUE TITLE
Audit Merkle Proof

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#51]
Trees stored per block:
* Transactions
* ~~State tree (merkle path not implemented in REST)~~ (treat in a separate issue)
* Receipts

## Proposal
**Check if a transaction is included in a block**

```
blockHttp
    .getTransactionMerkleAuditProof(height: uint, hash: string)
    .subscribe( merkleAuditProof => {    
        // Returns Observable<MerkleAuditProof>   
        console.log(merkleAuditProof.isConsistent()););
     }
````

Repeat for receipts.

**Comment by Vektrat** [comment]
this is kind of implemented in https://github.com/nemtech/nem2-sdk-typescript-javascript/tree/task/T516/merkle-tree - some changes are required

**Comment by evias** [comment]
will push a commit on this branch tomorrow with fixes related to rebase and **cow upgrade**.

**Comment by evias** [comment]
@rg911 please have a look here; do we have the needed methods in the SDK now ? 

If not, please prioritize integration of this :+1:

**Comment by rg911** [comment]
For receipt Merkle Proof, we need to serialize receipt object and hash it to be able to query the rest endpoint. Hash algorithm can be find out in https://github.com/nemtech/catapult-server/blob/8467be1485db44d60a9704ddf2eeab9050273911/src/catapult/model/ResolutionStatement.cpp#L48. Serialization will be integrated in to catbuffer

**Comment by Vektrat** [comment]
create a different issue for each kind of merkling, transactions is done differently than the other 2

**Comment by dgarcia360** [comment]
Re-opening this issue because the Merkle proof validation seems pending. See also this working snippet for the docs: https://gist.github.com/dgarcia360/3a5a388656dc0215ed10d2bfd328bdba#file-validatetransactioninblock-ts

**Comment by Vektrat** [comment]
also, i believe state trees are implemented as well in REST under

`/state/:state/hash/:hash/merkle`

what is to be considered is that at the moment this endpoint _only_ works for the `current` block due to a server limitation, hence why it lacks the `/block/:height` part

**Comment by dgarcia360** [comment]
Duplicated #449
