### ISSUE TITLE
Delegated Harvesting

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#52]
Delegated harvesting docs: https://nemtech.github.io/concepts/harvesting.html

### Activate / deactivate delegated harvesting

```
AccountLinkTransaction.create(
    Deadline.create(),
    LinkAction.Link, // Option Link or Unlink
    PublicAccount.createWithPublicKey(publicKey)
);
```

**Comment by dgarcia360** [comment]
Check how to know if delegated harvesting is enabled/disabled.

**Comment by evias** [comment]
PR for `AccountLinkTransaction` merged in library and SDK.
