### ISSUE TITLE
Fees

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#53]
https://nemtech.github.io/concepts/transaction.html#fees

Include ``max_fee`` field in the transaction.

```
TransferTransaction.create(
    Deadline.create(),  
    Address.createFromRawAddress('S..4'),
    [new Mosaic( Alias.create('alice.token'), UInt64.fromUint(10)],
    PlainMessage.create('Welcome To NEM'),
    NetworkType.MIJIN_TEST,
    NetworkCurrencyMosaic.createRelative(10), // maxFee);
```

**Comment by dgarcia360** [comment]
From Slack:

1. Replace `fee` for `max_fee` and make this parameter settable from the transaction model.

⚠️ If this could be an optional parameter, it won't break the current guides. Default to 0 if not set.

2. As `effective_fee = transaction::size * block::fee_multiplier`, it could be useful to have a method to calculate which is the transaction size, so that max_fee parameter can be set accordingly.

3. `TransactionHttp` (or another service) could provide with a function to calculate the fee paid given the transaction hash.

**Comment by evias** [comment]
Now maxFee field is left optional from all `create()` methods.

Also, the fee field has been renamed `maxFee` on all transaction constructors and unit tests were adapted.

Still missing: 

- transaction size calculator
- transaction paid reader

**Comment by evias** [comment]
Added `Transaction.size` getter to retrieve base transaction size.

Notes:

- Currently the `signature` and `signer` field are assumed to be set.
- Each class extending the Transaction class implemented an overload of the `size` getter to define their type-specific binary data sizes.

This is an implementation proposal for the `size` feature to avoid adding a `switch(this.type)` with many transaction type cases, and make use classes inheritance instead.

Unit tests have been added for each `size` call.

**Comment by evias** [comment]
Open PR #101 with implementation proposal to be merged.
