### ISSUE TITLE
Alias

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#55]
### Set/remove an alias to an address

```
AliasTransaction.createForAddress(
    Deadline.create(),
    AliasAction.Add, //AliasAction.Add or AliasAction.Remove
    namespaceId,
    address,
    NetworkType.MIJIN_TEST
);
```

### Set/remove an alias to a mosaic

```
AliasTransaction.createForMosaic(
    Deadline.create(),
    AliasAction.Add, //AliasAction.Add or AliasAction.Remove
    namespaceId,
    mosaicID,
    NetworkType.MIJIN_TEST
);
```

To define:

* Transfer a mosaic (alias)
* Transfer to an account (alias)
* Get address by alias
* Get mosaicId by alias
* Get mosaic alias
* Get address alias

**Comment by jorisadri** [comment]
A suggestion for the "To define" functions. 

### Get address by alias
```
NamespaceHttp.getLinkedAddress(alias);
  // returns address
```
### Get mosaicId by alias
```
NamespaceHttp.getLinkedmosaicId(alias);
  // returns mosaicId
```
###  Get address alias
```
AccountHttp.getLinkedAlias(address/publicKey);
  // returns namespace
```
###  Get mosaic alias
```
MosaicHttp.getLinkedAlias(mosaicId);
  // returns namespace
```

**Comment by dgarcia360** [comment]
@jorisadri +1 to the suggested functions. Since there are not specific endpoints for alias, seems a good idea reuse mosaic/namespace http instead of creating the ``AliasHttp``.

**Comment by evias** [comment]
Still missing *Http implementations.

**Comment by evias** [comment]
Missing tests for NamespaceHttp.getLinkedMosaicId and getLinkedAddress.

Also missing AccountHttp and MosaicHttp implementation.

**Comment by evias** [comment]
Fixed in PR #66

**Comment by evias** [comment]
merged in v0.10.3-1

**Comment by dgarcia360** [comment]
I open the issue again since ``transfer to an account (alias)`` is not possible yet. 

The recipient field should be an address or an alias (namespaceId) if possible.

**Comment by evias** [comment]
PR #83 created with implementation proposals for aliased recipients. :v:
