### ISSUE TITLE
Change secretlock sha512 to sha256

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#57]
Catapult native for cross-chain swaps will be sha3 256 instead of sha3 512.

* [HashType](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/6f71e1f4f88f995b94308da3d2c45ff31b5fccef/src/model/transaction/HashType.ts)

**Comment by rg911** [comment]
I am on this one as well
