### ISSUE TITLE
New lock hash algorithms for secret lock

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#58]
Add new lock hash algorithms for secret lock transaction https://github.com/nemtech/catapult-server/issues/13

* [HashType](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/6f71e1f4f88f995b94308da3d2c45ff31b5fccef/src/model/transaction/HashType.ts)

**Comment by rg911** [comment]
This one is with me now :D
