### ISSUE TITLE
How to sign announced aggregate bonded transactions?

### ISSUE THREAD

**Issue by aizaiz** [nemtech/nem2-sdk-typescript-javascript#6]
I'm trying to add a new cosignatory in a 2-of-2 multisig account with following this [documentation](https://nemtech.github.io/guides/account/modifying-a-multisig-account.html).

I'm using aggregate bonded to announce the transaction and because all cosigners have not signed it yet, I need to find a way how to sign announced aggregate bonded transactions.
I have read this documentation [Signing announced aggregate bonded transactions](https://nemtech.github.io/guides/transaction/signing-announced-aggregate-bonded-transactions.html) and tried to follow the instructions and run the code but it was not giving any response.

This is the code to sign announced aggregate bonded transactions

```// I used the private key of the account which didn't cosign the transaction yet
const privateKey = process.env.PRIVATE_KEY as string;

const account = Account.createFromPrivateKey(privateKey, NetworkType.MIJIN_TEST);
const accountHttp = new AccountHttp('http://localhost:3000');
const transactionHttp = new TransactionHttp('http://localhost:3000');


accountHttp.aggregateBondedTransactions(account.publicAccount)
    .flatMap((_) => _)
    .filter((_) => !_.signedByAccount(account.publicAccount))
    .map(transaction => cosignAggregateBondedTransaction(transaction, account))
    .flatMap(cosignatureSignedTransaction => transactionHttp.announceAggregateBondedCosignature(cosignatureSignedTransaction))
    .subscribe(announcedTransaction => console.log(announcedTransaction),
        err => console.error(err));

**Comment by aleixmorgadas** [comment]
I need you to check the next points:

1. are you running catapult on localhost? otherwise, you should point to the MIJIN_TEST network.
2. does `accountHttp.aggregateBondedTransactions(account.publicAccount)` return anything? It is possible that the account hasn't anything pending to be signed

**Comment by aizaiz** [comment]
1. Sorry I forgot to change the endpoint in the comment. in my code I use this endpoint http://api.beta.catapult.mijin.io:3000 

2.  `accountHttp.aggregateBondedTransactions(account.publicAccount)` does not return anything.
I checked the transaction using `nem2-cli account aggregatebonded --publickey thePublicKey`
I have tried with 3 public key:
if I use the publickey of the multisig account or cosigner which have signed the transaction it returns 
```AggregateTransaction:  InnerTransactions: [ ModifyMultisigAccountTransaction: MinApprovalDelta:0 MinRemovalDelta:0 Type:Add CosignatoryPublicAccount:SC6B4R-BE6KYT-FYK24B-LBWD2U-7I66RP-J6SMA3-6TEZ Signer:SDYBPP-SMISOB-WFQ5EC-RXAVDA-RLFNFT-XX4EAG-UTBK Deadline:2018-05-23 ] Signer:SCYQRW-UCQV2U-CNNQOG-MNQW5P-BWIANH-V45UZZ-D5GA Deadline:2018-05-23 Hash:DE951586DDBF3FA36E3580CB1EBFBBF6709FCA1276F0F2897A0C1DC43F3D8A5E

but if I use the public key of cosigner which haven't signed the transaction it will returns this
```There aren't aggregate bonded transaction

**Comment by aizaiz** [comment]
if I want to follow the example how to add a new cosignatory from this [documentation](https://nemtech.github.io/guides/account/modifying-a-multisig-account.html), how do I use this [documentation](https://nemtech.github.io/guides/transaction/signing-announced-aggregate-bonded-transactions.html) to cosign aggregate bonded transactions that require being signed by one of the cosignatory account?

**Comment by dgarcia360** [comment]
@aizaiz Sorry for the delay, I missed the latest message.

You have a 2-of-2 multisig. After announcing the aggregate transaction, another cosignatory should sign it to be included in a block.

You should fetch all pending aggregate bonded transactions from the **multisig account**. Afterwards, sign them with the second cosignatory.

`    const multisigAddress = Address.createFromRawAddress(rawAddress);
    const cosignatoryAccount = Account.createFromPrivateKey(cosingatoryAddress, NetworkType.MIJIN_TEST);
    
    accountHttp.aggregateBondedTransactions(multisigAddress)
      .flatMap((_) => _)
      .filter((_) => !_.signedByAccount(cosignatoryAccount.publicAccount))
      .map(transaction => cosignAggregateBondedTransaction(transaction, cosignatoryAccount))
      .flatMap(cosignatureSignedTransaction => transactionHttp.announceAggregateBondedCosignature(cosignatureSignedTransaction))
      .subscribe(announcedTransaction => console.log(announcedTransaction),
        err => console.error(err));
`

**Note:** You could get the list of the multisig accounts where an account is a cosigner using getMultisigAccountInfo method.

`const accountHttp = new AccountHttp('http://localhost:3000');

const address = Address.createFromRawAddress('SCSGBN-HYJD6P-KJHACX-3R2BI3-QUMMOY-QSNW5J-ICLK');

accountHttp
    .getMultisigAccountInfo(address)
    .subscribe(accountInfo => console.log(accountInfo), err => console.error(err));
`
