### ISSUE TITLE
unable to use nem2-sdk directly with react-native

### ISSUE THREAD

**Issue by sleepyOwl14** [nemtech/nem2-sdk-typescript-javascript#65]
When using the nem2-sdk with react-native, we expect the SDK will work

But when we start the Expo, Expo trying to compile and check the packages dependencies, error will prompt out saying `nodeJS built-in library not imported by default`

Please make a mobile friendly or browser standalone version of the SDK, so that we can use it with react-native and others mobile platform

**Comment by jabo38** [comment]
More info on this.

**Comment by rg911** [comment]
Closed. See integration solution referred by Jeff

**Comment by kahwooi** [comment]
Getting a flatbuffers related error when trying to sign a transaction.

`TypeError: undefined is not an object (evaluating 'new flatbuffers.Builder')`

Do you have any work around?

**Comment by evias** [comment]
@rg911 please have a look here

**Comment by evias** [comment]
this should be fixed since the deprecation of nem2-library.

Please, @kahwooi can you confirm ?

**Comment by kahwooi** [comment]
I am using version v0.11.6. Is nem2-library going to deprecated in the old version?

**Comment by rg911** [comment]
Nem2-Library has been migrated into SDK from v0.12.2. you can check the change log. 
So yes, 0.11.x is still using the library dependance

**Comment by kahwooi** [comment]
In order to use v0.12.x, I have to upgrade my network to support dragon protocol.

**Comment by kahwooi** [comment]
I have tested with v0.13.0, when I run on mobile I get "Unable to resolve module `bufferutil`" error:

`"message":"Unable to resolve module ``bufferutil`` from ``C:\\Users\\User\\App\\node_modules\\nem2-sdk\\node_modules\\ws\\lib\\buffer-util.js``: Module ``bufferutil`` does not exist in the Haste module map...`

**Comment by evias** [comment]
@rg911 please have a look here

**Comment by rg911** [comment]
yep. the `ws` package was 2 main version behind the latest. (5.0 -> 7.0)
I have a have a look

**Comment by kahwooi** [comment]
I am using :
```
"nem2-sdk": "0.13.0"
"react": "16.8.3",
"react-native": "0.59.9",
```
The ws use in node_module is version `1.1.5`

**Comment by rg911** [comment]
> I am using :
> 
> ```
> "nem2-sdk": "0.13.0"
> "react": "16.8.3",
> "react-native": "0.59.9",
> ```
> 
> The ws use in node_module is version `1.1.5`

ws used in SDK is versioned at @ 5.2.0, 1.1.5 looks wrong to me. You can probably try trashing your node_modules folder and npm install again

**Comment by kahwooi** [comment]
Yes I remove the node_module and reinstall all the dependencies, it give me version 1.1.5.

I also upgraded to ws@5.2.0, but the error remain.

**Comment by rg911** [comment]
@kahwooi Please try npm install bufferutil in your project see if it works.

**Comment by kahwooi** [comment]
Okay, it is solve after added the following package:

1. bufferutil
2. utf-8-validate
3. os 

The os package may need to map to the react-native-os package in the future if any related error.

**Comment by kahwooi** [comment]
When I tried to sign a transaction at mobile I get this error: 

`TypeError: undefined is not an object (evaluating '_this.Encoded_Block_Size')`

but it work when run using nodejs.

This line is the culprit: 

`const signedTransaction = account.sign(transaction, generationHash);`

**Comment by evias** [comment]
left-over from copying library features, probably can be fixed (`_this` is usually used because of scope issues, with TS this should not be a problem anymore @rg911 )

**Comment by kahwooi** [comment]
Where can I make changes, so I can get it solve by this week?

**Comment by evias** [comment]
this is the lower layer redirection: https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/model/account/Account.ts#L156

forwarding over to the Transaction base model: https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/model/transaction/Transaction.ts#L90

Now this method will use `transaction builders` which you can find in `src/infrastructure/builders` ; there is one transaction builder called `VerifiableTransactionBuilder`, this is the one used for signing transactions with `signWith`. Now this builder will use the `VerifiableTransaction` class also available in `src/infrastructure/builders` and with following `signTransaction` implementation: https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/infrastructure/builders/VerifiableTransaction.ts#L66

**I am not sure where this error happens, you will have to follow the path a bit deeper (KeyPair maybe),  but I believe this bug is due to the old JS implementation and you should be able to find the problem ** :+1:

**Comment by kahwooi** [comment]
@evias @rg911 

I am trying to sign TransferTransaction.

The error I found happen to be when it try to convert raw address string to Address: 

The error happend here, this.Encoded_Block_Size is undefined:

[https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/4d22d6fec1e4e722849b19480b843e8bd08f85be/src/core/format/Utilities.ts#L172](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/4d22d6fec1e4e722849b19480b843e8bd08f85be/src/core/format/Utilities.ts#L172)

**Comment by evias** [comment]
you cannot use the constant with `this`, you need to use `EncodedBlockSize` without this.

https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/4d22d6fec1e4e722849b19480b843e8bd08f85be/src/core/format/Utilities.ts#L58

Seems the flatbuffers error that pops up is something different. Please have a look at latest flatbuffers version to see how that can be used. `flatbuffers.Builders` should actually work. Maybe you must the import to:

```
import * as flatbuffers from 'flatbuffers';
```

**Comment by kahwooi** [comment]
RequireJS doesn't work, so import just like this: `import 'flatbuffers'` work in React-Native.

**Comment by rg911** [comment]
react-native checks dependancies during compile time, package existence checking is not possible during run time. Might be helpful to have a look at this https://github.com/sleepyOwl14/React-Native-using-nem2-sdk
