### ISSUE TITLE
Checking if a mosaic/namespace is expired

### ISSUE THREAD

**Issue by denizdurmus** [nemtech/nem2-sdk-typescript-javascript#7]
Right now there is no proper way to check if a mosaic/namespace is expired. As workaround, we can use (mosaic.getHeight + mosaic.getDuration) > blockhain.getHeight() to find out if a mosaic is expired (same applies for namespaces)

it would be much nicer if there is functionality to check the expiration by mosaic.isExpired()  and namespace.isExpired().

**Comment by kodty** [comment]
I think 'MosaicInfo.active' is what your looking for.

https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/model/mosaic/MosaicInfo.ts#L29

NamespaceInfo.active is the same. 

They both indicate if the mosaic/namespace is expired or not.

**Comment by kodty** [comment]
I think 'Mosaic.active' is what your looking for. 

https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/model/mosaic/MosaicInfo.ts#L29

It is the same for 'NamespaceInfo.active'. Both indicate whether the mosaic is expired or not.

**Comment by kodty** [comment]
https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/infrastructure/MosaicHttp.ts#L61 returns MosaicInfo which has Mosaic.active as a property. This indicates whether a mosaic is expired or not. The same applies to namespaces.

**Comment by denizdurmus** [comment]
thanks :) 
and same applies to other sdk as well, or it is only provided in ts/js sdk?

**Comment by denizdurmus** [comment]
actually, found it in 0.9.0 of java as well...
