### ISSUE TITLE
Verify Signature on nem2-sdk-typescript

### ISSUE THREAD

**Issue by aizaiz** [nemtech/nem2-sdk-typescript-javascript#8]
Hello @aleixmorgadas, I found this [verify signature function ](https://github.com/nemtech/nem2-library-js/blob/master/src/crypto/keyPair.js#L235)in nem2-library-js .

is there verify signature function in nem2-sdk-tipescript-javascript?

this is related to issue #3

**Comment by aizaiz** [comment]
Hi @aleixmorgadas I need this verify signature function to verify apostille on nem apostille library. are you working on it already or you got something else to do? if you are busy with something else, do you mind if I do this enhancement?

**Comment by aleixmorgadas** [comment]
Sorry for reply late.

Yes, I'm busy with other important task and I cannot do this one now, if you want to do it, we are glad to receive your help ^^

If you have questions to where do this things, just post your question here

**Comment by aizaiz** [comment]
Okay here is the questions ^^:
1. where should I put this function? new class/file or is there available class for this function?
2. about the minimum scope, do I have to recreate this verify signature function from javascript to typescript or can I just create a hood or wrapper where I can use this verify signature function using nem2-library? I would be glad if you add some of your envision here

**Comment by aleixmorgadas** [comment]
> 1. where should I put this function? new class/file or is there available class for this function?

I would start adding it in the [PublicAccount](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/model/account/PublicAccount.ts) class.

> 2. about the minimum scope, do I have to recreate this verify signature function from javascript to typescript or can I just create a hood or wrapper where I can use this verify signature function using nem2-library? I would be glad if you add some of your envision here

A wrapper of nem2-library is enough since there's already the feature there.

**Comment by aizaiz** [comment]
Hello @aleixmorgadas sorry for the delay, I just came back from holiday.
I have finished the code and this is the [pull request](https://github.com/nemtech/nem2-sdk-typescript-javascript/pull/10).
here is the preview of the code
```
import { convert, KeyPair } from 'nem2-library';
 
  /*
     * Verify a signature.
     *
     * @param {string} publicKey - The public key to use for verification.
     * @param {string} data - The data to verify.
     * @param {string} signature - The signature to verify.
     *
     * @return {boolean}  - True if the signature is valid, false otherwise.
     */

static verifySignature(publicKey: string, data: string, signature: string): boolean {
        if (!publicKey || !data || !signature) {
            throw new Error('Missing argument !');
        }

        if (publicKey.length !== 64 && publicKey.length !== 66) {
            throw new Error('Not a valid public key');
        }

        if (convert.isHexString(signature)) {
            throw new Error('Signature must be hexadecimal only !');
        }

        if (signature.length !== 128) {
            throw new Error('Signature length is incorrect !');
        }

        // Convert signature key to Uint8Array
        const _signature = convert.hexToUint8(signature);

        let _data;

        // Convert data to hex if data is not hex
        if (!convert.isHexString(data)) {
            _data = convert.utf8ToHex(data);
        }

        // Convert to Uint8Array
        _data = convert.hexToUint8(_data);

        return KeyPair.verify(publicKey, _data, _signature);
    }

**Comment by aleixmorgadas** [comment]
Hi @aizaiz, 
first of all, thank you for spending some time adding features to nem2-sdk :smile: 

No need to add the code here, we do a code review on each PR, so we'll see the code there ^_^
