### ISSUE TITLE
Determining if an alias was used in a transfer transaction

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-sdk-typescript-javascript#89]
[TransferTransaction creation from DTO](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/infrastructure/transaction/CreateTransactionFromDTO.ts#L119) does not take into account aliases.
 
How to determine if an alias was used, and get the corresponding NamespaceId:

1) **Address**:  If bit 0 of byte 0 is not set (like in 0x90), then it is a regular address. Else (e.g. 0x91) it represents a namespace id which starts at byte 1.

2) **Mosaic**: If the most significant bit is set, then is a NamespaceId.

**Comment by evias** [comment]
Fixed and merged in #91 :+1:

Published [nem2-sdk@v0.11.1](https://www.npmjs.com/package/nem2-sdk/v/0.11.1)
