### ISSUE TITLE
CreateTransactionFromDTO - MosaicAlias not mapping properly

### ISSUE THREAD

**Issue by rg911** [nemtech/nem2-sdk-typescript-javascript#97]
1. aliasAction property is wrong. should be *aliasAction* instead of *actionType*
2. mosaicId is parse from raw Uint64 should create instance of MosaicId instead
3. namespaceId, same issue as mosaicId

** similar issue on AddressAliasTransaction

**Comment by rg911** [comment]
I will be taking this one

**Comment by evias** [comment]
merged in master

will be integrated in later to be published v0.11.2
